// <auto-generated />
using System;
using LigaVolley.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigaVolley.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LigaVolleyDbContext))]
    [Migration("20260824151924_InitialSeasonAndDivision")]
    partial class InitialSeasonAndDivision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigaVolley.Domain.Divisions.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("division_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("gender");

                    b.Property<short>("LevelOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("level_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("DivisionId")
                        .HasName("PK_DIVISION");

                    b.HasAlternateKey("LevelOrder", "Gender")
                        .HasName("UQ_DIVISION_level_gender");

                    b.HasAlternateKey("Name", "Gender")
                        .HasName("UQ_DIVISION_name_gender");

                    b.ToTable("DIVISION", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_DIVISION_gender", "[gender] IN ('M','F')");

                            t.HasCheckConstraint("CK_DIVISION_level_order", "[level_order] > 0");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Seasons.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("SeasonId")
                        .HasName("PK_SEASON");

                    b.HasAlternateKey("Year")
                        .HasName("UQ_SEASON_year");

                    b.ToTable("SEASON", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_SEASON_dates", "[end_date] IS NULL OR [start_date] IS NULL OR [end_date] >= [start_date]");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
