// <auto-generated />
using System;
using LigaVolley.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LigaVolley.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LigaVolleyDbContext))]
    [Migration("20260824205634_AddTeamEntries")]
    partial class AddTeamEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LigaVolley.Domain.Clubs.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("club_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("short_name");

                    b.HasKey("ClubId")
                        .HasName("PK_CLUB");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_CLUB_name");

                    b.ToTable("CLUB", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", b =>
                {
                    b.Property<int>("CompetitionFormatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionFormatId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<short>("MaxTeams")
                        .HasColumnType("smallint")
                        .HasColumnName("max_teams");

                    b.Property<short>("MinTeams")
                        .HasColumnType("smallint")
                        .HasColumnName("min_teams");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("CompetitionFormatId")
                        .HasName("PK_COMPETITION_FORMAT");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_COMPETITION_FORMAT_code");

                    b.ToTable("COMPETITION_FORMAT", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_COMPETITION_FORMAT_team_range", "[min_teams] > 1 AND [max_teams] >= [min_teams]");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatGroup", b =>
                {
                    b.Property<int>("FormatGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatGroupId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("CarryOverMode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("carry_over_mode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<string>("FixtureMode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fixture_mode");

                    b.Property<int>("FormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("format_phase_id");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("group_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Rounds")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.HasKey("FormatGroupId");

                    b.HasAlternateKey("FormatGroupId", "CompetitionFormatId")
                        .HasName("UQ_FORMAT_GROUP_id_format");

                    b.HasIndex("FormatPhaseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_GROUP_code");

                    b.HasIndex("FormatPhaseId", "CompetitionFormatId");

                    b.ToTable("FORMAT_GROUP", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_FORMAT_GROUP_carry_over", "[carry_over_mode] IN ('NONE','ALL','QUALIFIED_ONLY')");

                            t.HasCheckConstraint("CK_FORMAT_GROUP_fixture_mode", "[fixture_mode] IN ('MIRRORED_HOME_AWAY','BALANCED_RANDOM')");

                            t.HasCheckConstraint("CK_FORMAT_GROUP_role", "[group_role] IN ('CHAMPIONSHIP','RELEGATION','OTHER')");

                            t.HasCheckConstraint("CK_FORMAT_GROUP_rounds", "[rounds] > 0");

                            t.HasCheckConstraint("CK_FORMAT_GROUP_sequence", "[sequence] > 0");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatMovementRule", b =>
                {
                    b.Property<int>("FormatMovementRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_movement_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatMovementRuleId"));

                    b.Property<bool>("AppliesIfTargetExists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("applies_if_target_exists");

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<short>("FromPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("from_position");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("movement_type");

                    b.Property<int?>("SourceFormatGroupId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_group_id");

                    b.Property<int?>("SourceFormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_phase_id");

                    b.Property<int?>("SourceFormatSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_series_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source_type");

                    b.Property<short>("TargetLevelDelta")
                        .HasColumnType("smallint")
                        .HasColumnName("target_level_delta");

                    b.Property<short>("ToPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("to_position");

                    b.HasKey("FormatMovementRuleId");

                    b.HasIndex("CompetitionFormatId");

                    b.HasIndex("SourceFormatGroupId", "CompetitionFormatId");

                    b.HasIndex("SourceFormatPhaseId", "CompetitionFormatId");

                    b.HasIndex("SourceFormatSeriesId", "CompetitionFormatId");

                    b.ToTable("FORMAT_MOVEMENT_RULE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPhase", b =>
                {
                    b.Property<int>("FormatPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_phase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatPhaseId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<string>("FixtureMode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fixture_mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhaseRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phase_role");

                    b.Property<string>("PhaseType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phase_type");

                    b.Property<short?>("Rounds")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.HasKey("FormatPhaseId");

                    b.HasAlternateKey("FormatPhaseId", "CompetitionFormatId")
                        .HasName("UQ_FORMAT_PHASE_id_format");

                    b.HasIndex("CompetitionFormatId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_PHASE_code");

                    b.ToTable("FORMAT_PHASE", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_FORMAT_PHASE_fixture_mode", "[fixture_mode] IS NULL OR [fixture_mode] IN ('MIRRORED_HOME_AWAY','BALANCED_RANDOM','PLAYOFF')");

                            t.HasCheckConstraint("CK_FORMAT_PHASE_role", "[phase_role] IN ('REGULAR','CHAMPIONSHIP','RELEGATION','SEMIFINAL','THIRD_PLACE','FINAL')");

                            t.HasCheckConstraint("CK_FORMAT_PHASE_round_robin", "[phase_type] <> 'ROUND_ROBIN' OR ([rounds] IS NOT NULL AND [fixture_mode] IS NOT NULL)");

                            t.HasCheckConstraint("CK_FORMAT_PHASE_rounds", "[rounds] IS NULL OR [rounds] > 0");

                            t.HasCheckConstraint("CK_FORMAT_PHASE_sequence", "[sequence] > 0");

                            t.HasCheckConstraint("CK_FORMAT_PHASE_type", "[phase_type] IN ('ROUND_ROBIN','GROUP_STAGE','PLAYOFF')");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", b =>
                {
                    b.Property<int>("FormatSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_series_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatSeriesId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<int>("FormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("format_phase_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<short>("Team1InitialWins")
                        .HasColumnType("smallint")
                        .HasColumnName("team1_initial_wins");

                    b.Property<short>("Team2InitialWins")
                        .HasColumnType("smallint")
                        .HasColumnName("team2_initial_wins");

                    b.Property<short>("WinsRequired")
                        .HasColumnType("smallint")
                        .HasColumnName("wins_required");

                    b.HasKey("FormatSeriesId");

                    b.HasAlternateKey("FormatSeriesId", "CompetitionFormatId")
                        .HasName("UQ_FORMAT_PLAYOFF_SERIES_id_format");

                    b.HasIndex("CompetitionFormatId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_PLAYOFF_SERIES_format_code");

                    b.HasIndex("FormatPhaseId", "CompetitionFormatId");

                    b.ToTable("FORMAT_PLAYOFF_SERIES", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_FORMAT_PLAYOFF_SERIES_initial_wins", "[team1_initial_wins] >= 0 AND [team2_initial_wins] >= 0 AND [team1_initial_wins] < [wins_required] AND [team2_initial_wins] < [wins_required]");

                            t.HasCheckConstraint("CK_FORMAT_PLAYOFF_SERIES_sequence", "[sequence] > 0");

                            t.HasCheckConstraint("CK_FORMAT_PLAYOFF_SERIES_wins_required", "[wins_required] > 0");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatQualificationRule", b =>
                {
                    b.Property<int>("QualificationRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("qualification_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualificationRuleId"));

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<short?>("FromPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("from_position");

                    b.Property<string>("SelectionMode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("selection_mode");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<int?>("SourceFormatGroupId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_group_id");

                    b.Property<int>("SourceFormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_phase_id");

                    b.Property<int?>("TargetFormatGroupId")
                        .HasColumnType("int")
                        .HasColumnName("target_format_group_id");

                    b.Property<int?>("TargetFormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("target_format_phase_id");

                    b.Property<int?>("TargetFormatSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("target_format_series_id");

                    b.Property<byte?>("TargetSide")
                        .HasColumnType("tinyint")
                        .HasColumnName("target_side");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("target_type");

                    b.Property<short?>("ToPosition")
                        .HasColumnType("smallint")
                        .HasColumnName("to_position");

                    b.HasKey("QualificationRuleId");

                    b.HasIndex("CompetitionFormatId");

                    b.HasIndex("SourceFormatGroupId", "CompetitionFormatId");

                    b.HasIndex("SourceFormatPhaseId", "CompetitionFormatId");

                    b.HasIndex("TargetFormatGroupId", "CompetitionFormatId");

                    b.HasIndex("TargetFormatPhaseId", "CompetitionFormatId");

                    b.HasIndex("TargetFormatSeriesId", "CompetitionFormatId");

                    b.ToTable("FORMAT_QUALIFICATION_RULE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatScoringRule", b =>
                {
                    b.Property<int>("FormatScoringRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_scoring_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatScoringRuleId"));

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<byte>("LoserSets")
                        .HasColumnType("tinyint")
                        .HasColumnName("loser_sets");

                    b.Property<short>("LoserTablePoints")
                        .HasColumnType("smallint")
                        .HasColumnName("loser_table_points");

                    b.Property<byte>("WinnerSets")
                        .HasColumnType("tinyint")
                        .HasColumnName("winner_sets");

                    b.Property<short>("WinnerTablePoints")
                        .HasColumnType("smallint")
                        .HasColumnName("winner_table_points");

                    b.HasKey("FormatScoringRuleId");

                    b.HasIndex("CompetitionFormatId", "WinnerSets", "LoserSets")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_SCORING_RULE_score");

                    b.ToTable("FORMAT_SCORING_RULE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatSeriesParticipantSource", b =>
                {
                    b.Property<int>("FormatSeriesParticipantSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_series_participant_source_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatSeriesParticipantSourceId"));

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<int>("SourceFormatSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("source_format_series_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source_type");

                    b.Property<int>("TargetFormatSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("target_format_series_id");

                    b.Property<byte>("TargetSide")
                        .HasColumnType("tinyint")
                        .HasColumnName("target_side");

                    b.HasKey("FormatSeriesParticipantSourceId");

                    b.HasIndex("SourceFormatSeriesId", "CompetitionFormatId");

                    b.HasIndex("TargetFormatSeriesId", "CompetitionFormatId");

                    b.HasIndex("TargetFormatSeriesId", "TargetSide")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_SERIES_SOURCE_target_side");

                    b.ToTable("FORMAT_SERIES_PARTICIPANT_SOURCE", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_FORMAT_SERIES_SOURCE_not_same", "[target_format_series_id] <> [source_format_series_id]");

                            t.HasCheckConstraint("CK_FORMAT_SERIES_SOURCE_side", "[target_side] IN (1,2)");

                            t.HasCheckConstraint("CK_FORMAT_SERIES_SOURCE_type", "[source_type] IN ('SERIES_WINNER','SERIES_LOSER')");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatTiebreakRule", b =>
                {
                    b.Property<int>("FormatTiebreakRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("format_tiebreak_rule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormatTiebreakRuleId"));

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("criterion");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<string>("SortDirection")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("sort_direction");

                    b.HasKey("FormatTiebreakRuleId");

                    b.HasIndex("CompetitionFormatId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("UQ_FORMAT_TIEBREAK_RULE_sequence");

                    b.ToTable("FORMAT_TIEBREAK_RULE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.Competition", b =>
                {
                    b.Property<int>("CompetitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("competition_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionId"));

                    b.Property<int>("CompetitionFormatId")
                        .HasColumnType("int")
                        .HasColumnName("competition_format_id");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int")
                        .HasColumnName("division_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("period_type");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("CompetitionId");

                    b.HasIndex("CompetitionFormatId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("SeasonId");

                    b.ToTable("COMPETITION", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_COMPETITION_dates", "[end_date] IS NULL OR [start_date] IS NULL OR [end_date] >= [start_date]");

                            t.HasCheckConstraint("CK_COMPETITION_status", "[status] IN ('DRAFT','SCHEDULED','IN_PROGRESS','FINISHED','CANCELLED')");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPhase", b =>
                {
                    b.Property<int>("CompetitionPhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("competition_phase_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionPhaseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int")
                        .HasColumnName("competition_id");

                    b.Property<string>("FixtureMode")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fixture_mode");

                    b.Property<int>("FormatPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("format_phase_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhaseRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phase_role");

                    b.Property<string>("PhaseType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phase_type");

                    b.Property<short?>("Rounds")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("CompetitionPhaseId");

                    b.HasIndex("FormatPhaseId");

                    b.HasIndex("CompetitionId", "Code")
                        .IsUnique();

                    b.ToTable("COMPETITION_PHASE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPhaseGroup", b =>
                {
                    b.Property<int>("PhaseGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("phase_group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhaseGroupId"));

                    b.Property<string>("CarryOverMode")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("carry_over_mode");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("competition_phase_id");

                    b.Property<string>("FixtureMode")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fixture_mode");

                    b.Property<int>("FormatGroupId")
                        .HasColumnType("int")
                        .HasColumnName("format_group_id");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("group_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Rounds")
                        .HasColumnType("smallint")
                        .HasColumnName("rounds");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.HasKey("PhaseGroupId");

                    b.HasIndex("FormatGroupId");

                    b.HasIndex("CompetitionPhaseId", "Code")
                        .IsUnique();

                    b.ToTable("PHASE_GROUP", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPlayoffSeries", b =>
                {
                    b.Property<int>("PlayoffSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("playoff_series_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayoffSeriesId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("code");

                    b.Property<int>("CompetitionPhaseId")
                        .HasColumnType("int")
                        .HasColumnName("competition_phase_id");

                    b.Property<int>("FormatSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("format_series_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<short>("Sequence")
                        .HasColumnType("smallint")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<short>("Team1InitialWins")
                        .HasColumnType("smallint")
                        .HasColumnName("team1_initial_wins");

                    b.Property<short>("Team2InitialWins")
                        .HasColumnType("smallint")
                        .HasColumnName("team2_initial_wins");

                    b.Property<short>("WinsRequired")
                        .HasColumnType("smallint")
                        .HasColumnName("wins_required");

                    b.HasKey("PlayoffSeriesId");

                    b.HasIndex("FormatSeriesId");

                    b.HasIndex("CompetitionPhaseId", "Code")
                        .IsUnique();

                    b.ToTable("PLAYOFF_SERIES", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionSeriesParticipantSource", b =>
                {
                    b.Property<int>("SeriesParticipantSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("series_participant_source_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesParticipantSourceId"));

                    b.Property<int>("SourcePlayoffSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("source_playoff_series_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source_type");

                    b.Property<int>("TargetPlayoffSeriesId")
                        .HasColumnType("int")
                        .HasColumnName("target_playoff_series_id");

                    b.Property<byte>("TargetSide")
                        .HasColumnType("tinyint")
                        .HasColumnName("target_side");

                    b.HasKey("SeriesParticipantSourceId");

                    b.HasIndex("SourcePlayoffSeriesId");

                    b.HasIndex("TargetPlayoffSeriesId", "TargetSide")
                        .IsUnique();

                    b.ToTable("SERIES_PARTICIPANT_SOURCE", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_SERIES_PARTICIPANT_SOURCE_side", "[target_side] IN (1,2)");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Divisions.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("division_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("gender");

                    b.Property<short>("LevelOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("level_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("DivisionId")
                        .HasName("PK_DIVISION");

                    b.HasAlternateKey("LevelOrder", "Gender")
                        .HasName("UQ_DIVISION_level_gender");

                    b.HasAlternateKey("Name", "Gender")
                        .HasName("UQ_DIVISION_name_gender");

                    b.ToTable("DIVISION", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_DIVISION_gender", "[gender] IN ('M','F')");

                            t.HasCheckConstraint("CK_DIVISION_level_order", "[level_order] > 0");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Seasons.Season", b =>
                {
                    b.Property<int>("SeasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("season_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeasonId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("SeasonId")
                        .HasName("PK_SEASON");

                    b.HasAlternateKey("Year")
                        .HasName("UQ_SEASON_year");

                    b.ToTable("SEASON", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_SEASON_dates", "[end_date] IS NULL OR [start_date] IS NULL OR [end_date] >= [start_date]");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.TeamEntries.TeamEntry", b =>
                {
                    b.Property<int>("TeamEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_entry_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamEntryId"));

                    b.Property<int>("CompetitionId")
                        .HasColumnType("int")
                        .HasColumnName("competition_id");

                    b.Property<short?>("Seed")
                        .HasColumnType("smallint")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("REGISTERED")
                        .HasColumnName("status");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("TeamEntryId")
                        .HasName("PK_TEAM_ENTRY");

                    b.HasAlternateKey("TeamEntryId", "CompetitionId")
                        .HasName("UQ_TEAM_ENTRY_id_comp");

                    b.HasIndex("TeamId");

                    b.HasIndex("CompetitionId", "Status")
                        .HasDatabaseName("IX_TEAM_ENTRY_competition");

                    b.HasIndex("CompetitionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("UQ_TEAM_ENTRY");

                    b.ToTable("TEAM_ENTRY", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_TEAM_ENTRY_seed", "[seed] IS NULL OR [seed] > 0");

                            t.HasCheckConstraint("CK_TEAM_ENTRY_status", "[status] IN ('REGISTERED','ACTIVE','WITHDRAWN','DISQUALIFIED')");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Teams.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int")
                        .HasColumnName("club_id");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("TeamId")
                        .HasName("PK_TEAM");

                    b.HasIndex("ClubId");

                    b.HasIndex("Name", "Gender")
                        .IsUnique()
                        .HasDatabaseName("UQ_TEAM_name_gender");

                    b.ToTable("TEAM", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_TEAM_gender", "[gender] IN ('M','F')");
                        });
                });

            modelBuilder.Entity("LigaVolley.Domain.Venues.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("venue_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("name");

                    b.HasKey("VenueId")
                        .HasName("PK_VENUE");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_VENUE_name");

                    b.ToTable("VENUE", "dbo");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatGroup", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", null)
                        .WithMany("Groups")
                        .HasForeignKey("FormatPhaseId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatPhaseId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatMovementRule", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", null)
                        .WithMany("MovementRules")
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatGroup", "SourceGroup")
                        .WithMany()
                        .HasForeignKey("SourceFormatGroupId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatGroupId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", "SourcePhase")
                        .WithMany()
                        .HasForeignKey("SourceFormatPhaseId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatPhaseId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", "SourceSeries")
                        .WithMany()
                        .HasForeignKey("SourceFormatSeriesId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatSeriesId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceGroup");

                    b.Navigation("SourcePhase");

                    b.Navigation("SourceSeries");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPhase", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", null)
                        .WithMany("Phases")
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", null)
                        .WithMany("Series")
                        .HasForeignKey("FormatPhaseId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatPhaseId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatQualificationRule", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", null)
                        .WithMany("QualificationRules")
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatGroup", "SourceGroup")
                        .WithMany()
                        .HasForeignKey("SourceFormatGroupId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatGroupId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", "SourcePhase")
                        .WithMany()
                        .HasForeignKey("SourceFormatPhaseId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatPhaseId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatGroup", "TargetGroup")
                        .WithMany()
                        .HasForeignKey("TargetFormatGroupId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatGroupId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", "TargetPhase")
                        .WithMany()
                        .HasForeignKey("TargetFormatPhaseId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatPhaseId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", "TargetSeries")
                        .WithMany()
                        .HasForeignKey("TargetFormatSeriesId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatSeriesId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourceGroup");

                    b.Navigation("SourcePhase");

                    b.Navigation("TargetGroup");

                    b.Navigation("TargetPhase");

                    b.Navigation("TargetSeries");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatScoringRule", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", null)
                        .WithMany("ScoringRules")
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatSeriesParticipantSource", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", "SourceSeries")
                        .WithMany()
                        .HasForeignKey("SourceFormatSeriesId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatSeriesId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", null)
                        .WithMany("ParticipantSources")
                        .HasForeignKey("TargetFormatSeriesId", "CompetitionFormatId")
                        .HasPrincipalKey("FormatSeriesId", "CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSeries");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatTiebreakRule", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", null)
                        .WithMany("TiebreakRules")
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.Competition", b =>
                {
                    b.HasOne("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", "CompetitionFormat")
                        .WithMany()
                        .HasForeignKey("CompetitionFormatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.Divisions.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.Seasons.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionFormat");

                    b.Navigation("Division");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPhase", b =>
                {
                    b.HasOne("LigaVolley.Domain.Competitions.Competition", null)
                        .WithMany("Phases")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPhase", "FormatPhase")
                        .WithMany()
                        .HasForeignKey("FormatPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormatPhase");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPhaseGroup", b =>
                {
                    b.HasOne("LigaVolley.Domain.Competitions.CompetitionPhase", null)
                        .WithMany("Groups")
                        .HasForeignKey("CompetitionPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatGroup", "FormatGroup")
                        .WithMany()
                        .HasForeignKey("FormatGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormatGroup");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPlayoffSeries", b =>
                {
                    b.HasOne("LigaVolley.Domain.Competitions.CompetitionPhase", null)
                        .WithMany("Series")
                        .HasForeignKey("CompetitionPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", "FormatSeries")
                        .WithMany()
                        .HasForeignKey("FormatSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormatSeries");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionSeriesParticipantSource", b =>
                {
                    b.HasOne("LigaVolley.Domain.Competitions.CompetitionPlayoffSeries", "SourceSeries")
                        .WithMany()
                        .HasForeignKey("SourcePlayoffSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LigaVolley.Domain.Competitions.CompetitionPlayoffSeries", null)
                        .WithMany("ParticipantSources")
                        .HasForeignKey("TargetPlayoffSeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceSeries");
                });

            modelBuilder.Entity("LigaVolley.Domain.TeamEntries.TeamEntry", b =>
                {
                    b.HasOne("LigaVolley.Domain.Competitions.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TEAM_ENTRY_COMPETITION");

                    b.HasOne("LigaVolley.Domain.Teams.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TEAM_ENTRY_TEAM");

                    b.Navigation("Competition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LigaVolley.Domain.Teams.Team", b =>
                {
                    b.HasOne("LigaVolley.Domain.Clubs.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_TEAM_CLUB");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.CompetitionFormat", b =>
                {
                    b.Navigation("MovementRules");

                    b.Navigation("Phases");

                    b.Navigation("QualificationRules");

                    b.Navigation("ScoringRules");

                    b.Navigation("TiebreakRules");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPhase", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LigaVolley.Domain.CompetitionFormats.FormatPlayoffSeries", b =>
                {
                    b.Navigation("ParticipantSources");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.Competition", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPhase", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("LigaVolley.Domain.Competitions.CompetitionPlayoffSeries", b =>
                {
                    b.Navigation("ParticipantSources");
                });
#pragma warning restore 612, 618
        }
    }
}
