import { useEffect, useState } from 'react';
import { BrowserRouter, Link, NavLink, Outlet, Route, Routes, useLocation, useNavigate, useOutletContext, useParams, useSearchParams } from 'react-router-dom';
import { publicApi } from '../api/publicApi';
import type { Competition, CompetitionSummary, MatchDetail, Season, SeasonHome as SeasonHomeDto, SeasonMatch } from '../api/types';
import { PublicMatchLive } from '../live/PublicMatchLive';
import { EmptyState, MatchCard, PageHeader, StatusBadge, TeamLogo } from './components';
import { FixtureResults } from './FixtureResults'; import { StandingsResults } from './StandingsResults'; import { PlayoffsResults } from './PlayoffsResults'; import './app.css';

function Load<T>({ run, children }: { run: () => Promise<T>; children: (value: T) => React.ReactNode }) { const [data, setData] = useState<T>(); const [error, setError] = useState(false); useEffect(() => { let active = true; run().then(value => active && setData(value)).catch(() => active && setError(true)); return () => { active = false; }; }, []); return error ? <p className="load-state is-error" role="alert">No se pudo cargar la información.</p> : data ? children(data) : <p className="load-state" role="status">Cargando información…</p>; }
type Context = { competition?: CompetitionSummary; setCompetition: (competition?: CompetitionSummary) => void };
function PublicLayout() { const navigate = useNavigate(), location = useLocation(); const [seasons, setSeasons] = useState<Season[]>(); const [error, setError] = useState(false); const [open, setOpen] = useState(false); const [competition, setCompetition] = useState<CompetitionSummary>(); const routeSeasonId = /^\/seasons\/(\d+)$/.exec(location.pathname)?.[1]; const seasonId = routeSeasonId ?? new URLSearchParams(location.search).get('seasonId') ?? (competition ? String(competition.season.seasonId) : ''); useEffect(() => { publicApi.seasons().then(setSeasons).catch(() => setError(true)); }, []); useEffect(() => setOpen(false), [location.pathname, location.search, location.hash]); useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && setOpen(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []); const nav = <nav className="public-nav" aria-label="Navegación pública"><NavLink to="/" end>Inicio</NavLink><NavLink to={seasonId ? `/competitions?seasonId=${seasonId}` : '/competitions'}>Competiciones</NavLink>{competition && <div className="competition-nav"><p>{competition.name}</p><NavLink to={`/competitions/${competition.competitionId}`} end>Resumen</NavLink><NavLink to={`/competitions/${competition.competitionId}/fixture`}>Fixture / Resultados</NavLink><NavLink to={`/competitions/${competition.competitionId}/standings`}>Posiciones</NavLink><NavLink to={`/competitions/${competition.competitionId}/playoffs`}>Playoffs</NavLink></div>}</nav>; return <div className="public-shell"><aside className="public-sidebar"><Link className="shell-brand" to="/">LigaVolley</Link><label className="season-picker">Temporada<select aria-label="Temporada" value={seasonId} onChange={event => { setCompetition(undefined); navigate(event.target.value ? `/seasons/${event.target.value}` : '/competitions'); }} disabled={!seasons}><option value="">{error ? 'No disponible' : seasons ? 'Todas' : 'Cargando…'}</option>{seasons?.map(season => <option key={season.seasonId} value={season.seasonId}>{season.year} · {season.name}</option>)}</select></label>{nav}</aside><header className="mobile-shell"><Link className="shell-brand" to="/">LigaVolley</Link><button aria-label="Abrir navegación" aria-expanded={open} onClick={() => setOpen(value => !value)}>☰</button></header>{open && <div className="mobile-drawer">{nav}</div>}<main className="shell-content"><Outlet context={{ competition, setCompetition } satisfies Context} /></main></div>; }
function Home() { return <Load run={publicApi.seasons}>{seasons => <><PageHeader title="Temporadas" />{seasons.length ? <div className="cards">{seasons.map(season => <Link className="card" key={season.seasonId} to={`/seasons/${season.seasonId}`}><b>{season.name}</b><span>{season.year}</span></Link>)}</div> : <EmptyState>No hay temporadas públicas para mostrar.</EmptyState>}</>}</Load>; }
function SeasonMatches({ title, matches, empty }: { title: string; matches: SeasonMatch[]; empty: string }) { return <section><h2>{title}</h2>{matches.length ? matches.map(match => <div className="season-match" key={match.matchId}><small>{match.competitionName}</small><MatchCard match={match} /></div>) : <EmptyState>{empty}</EmptyState>}</section>; }
function SeasonHomeContent({ home }: { home: SeasonHomeDto }) { const cards = (items: CompetitionSummary[]) => <div className="cards">{items.map(item => <Link className="card" key={item.competitionId} to={`/competitions/${item.competitionId}`}><b>{item.name}</b><span>{item.division.name}</span><StatusBadge status={item.status} /></Link>)}</div>; return <><PageHeader context="Temporada" title={home.season.name} meta={home.season.year} /><section><h2>Competiciones activas</h2>{home.activeCompetitions.length ? cards(home.activeCompetitions) : <EmptyState>No hay competiciones activas.</EmptyState>}</section><SeasonMatches title="En juego" matches={home.liveMatches} empty="No hay partidos en juego." /><SeasonMatches title="Próximos partidos" matches={home.upcomingMatches} empty="No hay próximos partidos programados." /><SeasonMatches title="Últimos resultados" matches={home.recentResults} empty="Todavía no hay resultados." /><section><h2>Finalizadas</h2>{home.finishedCompetitions.length ? cards(home.finishedCompetitions) : <EmptyState>No hay competiciones finalizadas.</EmptyState>}</section></>; }
function SeasonHome() { const id = Number(useParams().seasonId); return <Load key={id} run={() => publicApi.seasonHome(id)}>{home => <SeasonHomeContent home={home} />}</Load>; }
function Competitions() { const [query] = useSearchParams(); const seasonId = Number(query.get('seasonId')) || undefined; return <Load key={seasonId} run={() => publicApi.competitions(seasonId)}>{items => <><PageHeader context={seasonId ? 'Temporada seleccionada' : undefined} title="Competiciones" />{items.length ? <div className="cards">{items.map(item => <Link className="card" key={item.competitionId} to={`/competitions/${item.competitionId}`}><b>{item.name}</b><span>{item.season.name} · {item.division.name}</span><StatusBadge status={item.status} /></Link>)}</div> : <EmptyState>No hay competiciones públicas para mostrar.</EmptyState>}</>}</Load>; }
function CompetitionContext({ competition, children }: { competition: Competition; children: React.ReactNode }) { const { setCompetition } = useOutletContext<Context>(); useEffect(() => { setCompetition(competition); return () => setCompetition(undefined); }, [competition, setCompetition]); return <>{children}</>; }
function CompetitionPage() { const id = Number(useParams().competitionId); return <Load key={id} run={() => publicApi.competition(id)}>{competition => <CompetitionContext competition={competition}><PageHeader context={`${competition.season.name} · ${competition.division.name}`} title={competition.name} meta={<StatusBadge status={competition.status} />} /><nav className="summary-links" aria-label="Secciones de competencia"><Link to={`/competitions/${id}/fixture`}>Fixture y resultados</Link><Link to={`/competitions/${id}/standings`}>Posiciones</Link>{competition.phases.some(phase => phase.playoffSeries.length > 0) && <Link to={`/competitions/${id}/playoffs`}>Playoffs</Link>}</nav><section><h2>Equipos</h2>{competition.teams.length ? <div className="team-grid">{competition.teams.map(team => <div className="team-chip" key={team.teamEntryId}><TeamLogo team={team} /><span>{team.teamName}</span></div>)}</div> : <EmptyState>No hay equipos publicados.</EmptyState>}</section><section><h2>Próximos partidos</h2>{competition.upcomingMatches.length ? competition.upcomingMatches.map(match => <MatchCard key={match.matchId} match={match} />) : <EmptyState>No hay próximos partidos programados.</EmptyState>}</section><section><h2>Resultados recientes</h2>{competition.recentResults.length ? competition.recentResults.map(match => <MatchCard key={match.matchId} match={match} />) : <EmptyState>Todavía no hay resultados.</EmptyState>}</section></CompetitionContext>}</Load>; }
function CompetitionSection({ title, children }: { title: string; children: (competition: Competition) => React.ReactNode }) { const id = Number(useParams().competitionId); return <Load key={id} run={() => publicApi.competition(id)}>{competition => <CompetitionContext competition={competition}><PageHeader context={competition.name} title={title} meta={`${competition.season.name} · ${competition.division.name}`} />{children(competition)}</CompetitionContext>}</Load>; }
function FixturePage() { const id = Number(useParams().competitionId); return <CompetitionSection title="Fixture y resultados">{() => <Load key={id} run={() => publicApi.fixture(id)}>{fixture => <FixtureResults fixture={fixture} />}</Load>}</CompetitionSection>; }
function StandingsPage() { const id = Number(useParams().competitionId); return <CompetitionSection title="Posiciones">{() => <Load key={id} run={() => publicApi.standings(id)}>{standings => <StandingsResults standings={standings} />}</Load>}</CompetitionSection>; }
function PlayoffsPage() { return <CompetitionSection title="Playoffs">{competition => <PlayoffsResults competition={competition} />}</CompetitionSection>; }
function MatchPage() { const id = Number(useParams().matchId); return <Load key={id} run={() => publicApi.match(id)}>{match => <MatchContent match={match} />}</Load>; }
function MatchContent({ match }: { match: MatchDetail }) { const { setCompetition } = useOutletContext<Context>(); useEffect(() => { setCompetition({ competitionId: match.competition.competitionId, name: match.competition.competitionName, season: { seasonId: match.competition.seasonId ?? match.competition.seasonYear, year: match.competition.seasonYear, name: String(match.competition.seasonYear) }, division: { divisionId: 0, name: match.competition.divisionName, levelOrder: 0, gender: match.competition.gender }, periodType: '', status: match.status }); return () => setCompetition(undefined); }, [match, setCompetition]); const scope = [match.scope.phaseName, match.scope.phaseGroupName, match.scope.seriesName].filter(Boolean).join(' · '); return <div className="public-match-page"><PageHeader back={<Link to={`/competitions/${match.competition.competitionId}`}>← {match.competition.competitionName}</Link>} context={`${match.competition.seasonYear} · ${match.competition.divisionName}`} title={scope} meta={`${match.matchDate ? new Date(match.matchDate).toLocaleString() : 'Fecha a confirmar'} · ${match.venue?.name ?? 'Sede a confirmar'}`} /><PublicMatchLive match={match} /></div>; }
export default function App() { return <BrowserRouter><Routes><Route element={<PublicLayout />}><Route path="/" element={<Home />} /><Route path="/seasons/:seasonId" element={<SeasonHome />} /><Route path="/competitions" element={<Competitions />} /><Route path="/competitions/:competitionId" element={<CompetitionPage />} /><Route path="/competitions/:competitionId/fixture" element={<FixturePage />} /><Route path="/competitions/:competitionId/standings" element={<StandingsPage />} /><Route path="/competitions/:competitionId/playoffs" element={<PlayoffsPage />} /><Route path="/matches/:matchId" element={<MatchPage />} /></Route></Routes></BrowserRouter>; }
