import { useEffect, useState } from 'react';
import { BrowserRouter, Link, NavLink, Outlet, Route, Routes, useLocation, useNavigate, useOutletContext, useParams, useSearchParams } from 'react-router-dom';
import { publicApi } from '../api/publicApi';
import type { Competition, CompetitionSummary, Fixture, MatchDetail, Season, SeasonHome as SeasonHomeDto, SeasonMatch, Standings } from '../api/types';
import { PublicMatchLive } from '../live/PublicMatchLive';
import { Bracket, MatchCard, StandingsTableView, label } from './components';
import './app.css';

function Load<T>({ run, children }: { run: () => Promise<T>; children: (value: T) => React.ReactNode }) {
  const [data, setData] = useState<T>(); const [error, setError] = useState('');
  useEffect(() => { run().then(setData).catch(() => setError('No se pudo cargar la información.')); }, []);
  return error ? <p>{error}</p> : data ? children(data) : <p>Cargando…</p>;
}

type Context = { competition?: CompetitionSummary; setCompetition: (competition?: CompetitionSummary) => void };

function CompetitionLink({ competitionId, section, children }: { competitionId: number; section: string; children: React.ReactNode }) {
  const location = useLocation(); const active = location.pathname === `/competitions/${competitionId}` && (location.hash === `#${section}` || (!location.hash && section === 'fixture'));
  return <Link className={active ? 'active' : ''} aria-current={active ? 'page' : undefined} to={`/competitions/${competitionId}#${section}`}>{children}</Link>;
}

function PublicLayout() {
  const navigate = useNavigate(), location = useLocation(); const [seasons, setSeasons] = useState<Season[]>(); const [error, setError] = useState(false); const [open, setOpen] = useState(false); const [competition, setCompetition] = useState<CompetitionSummary>();
  const routeSeasonId = /^\/seasons\/(\d+)$/.exec(location.pathname)?.[1]; const seasonId = routeSeasonId ?? new URLSearchParams(location.search).get('seasonId') ?? (competition ? String(competition.season.seasonId) : '');
  useEffect(() => { publicApi.seasons().then(setSeasons).catch(() => setError(true)); }, []); useEffect(() => setOpen(false), [location.pathname, location.search, location.hash]);
  useEffect(() => { const close = (event: KeyboardEvent) => event.key === 'Escape' && setOpen(false); window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const change = (id: string) => { setCompetition(undefined); navigate(id ? `/seasons/${id}` : '/competitions'); };
  const nav = <nav className="public-nav" aria-label="Navegación pública"><NavLink to="/" end>Inicio</NavLink><NavLink to={seasonId ? `/competitions?seasonId=${seasonId}` : '/competitions'}>Competiciones</NavLink>{competition && <div className="competition-nav"><p>{competition.name}</p><CompetitionLink competitionId={competition.competitionId} section="fixture">Fixture / Resultados</CompetitionLink><CompetitionLink competitionId={competition.competitionId} section="standings">Posiciones</CompetitionLink><CompetitionLink competitionId={competition.competitionId} section="playoffs">Playoffs</CompetitionLink></div>}</nav>;
  return <div className="public-shell"><aside className="public-sidebar"><Link className="shell-brand" to="/">LigaVolley</Link><label className="season-picker">Temporada<select aria-label="Temporada" value={seasonId} onChange={event => change(event.target.value)} disabled={!seasons}><option value="">{error ? 'No disponible' : seasons ? 'Todas' : 'Cargando…'}</option>{seasons?.map(season => <option key={season.seasonId} value={season.seasonId}>{season.year} · {season.name}</option>)}</select></label>{nav}</aside><header className="mobile-shell"><Link className="shell-brand" to="/">LigaVolley</Link><button aria-label="Abrir navegación" aria-expanded={open} onClick={() => setOpen(value => !value)}>☰</button></header>{open && <div className="mobile-drawer">{nav}</div>}<main className="shell-content"><Outlet context={{ competition, setCompetition } satisfies Context} /></main></div>;
}

function Home() { return <Load run={publicApi.seasons}>{seasons => <><h1>Temporadas</h1><div className="cards">{seasons.map(season => <Link className="card" key={season.seasonId} to={`/seasons/${season.seasonId}`}><b>{season.name}</b><span>{season.year}</span></Link>)}</div></>}</Load>; }

function SeasonMatches({ title, matches, empty }: { title: string; matches: SeasonMatch[]; empty: string }) { return <section><h2>{title}</h2>{matches.length ? matches.map(match => <div key={match.matchId}><small>{match.competitionName}</small><MatchCard match={match} /></div>) : <p>{empty}</p>}</section>; }
function SeasonHomeContent({ home }: { home: SeasonHomeDto }) { return <><header className="hero"><p>{home.season.year}</p><h1>{home.season.name}</h1></header><section><h2>Competiciones activas</h2>{home.activeCompetitions.length ? home.activeCompetitions.map(competition => <Link className="card" key={competition.competitionId} to={`/competitions/${competition.competitionId}`}><b>{competition.name}</b><span>{competition.division.name} · {label(competition.status)}</span></Link>) : <p>No hay competiciones activas.</p>}</section><SeasonMatches title="En juego" matches={home.liveMatches} empty="No hay partidos en juego." /><SeasonMatches title="Próximos partidos" matches={home.upcomingMatches} empty="No hay próximos partidos programados." /><SeasonMatches title="Últimos resultados" matches={home.recentResults} empty="Todavía no hay resultados." /><section><h2>Finalizadas</h2>{home.finishedCompetitions.length ? home.finishedCompetitions.map(competition => <p key={competition.competitionId}><Link to={`/competitions/${competition.competitionId}`}>{competition.name}</Link></p>) : <p>No hay competiciones finalizadas.</p>}</section></>; }
function SeasonHome() { const id = Number(useParams().seasonId); return <Load key={id} run={() => publicApi.seasonHome(id)}>{home => <SeasonHomeContent home={home} />}</Load>; }

function Competitions() { const [query] = useSearchParams(); const seasonId = Number(query.get('seasonId')) || undefined; return <Load key={seasonId} run={() => publicApi.competitions(seasonId)}>{items => <><h1>Competiciones</h1><div className="cards">{items.map(competition => <Link className="card" key={competition.competitionId} to={`/competitions/${competition.competitionId}`}><b>{competition.name}</b><span>{competition.season.name} · {competition.division.name}</span><em>{label(competition.status)}</em></Link>)}</div></>}</Load>; }
function CompetitionPage() { const id = Number(useParams().competitionId); return <Load key={id} run={() => Promise.all([publicApi.competition(id), publicApi.fixture(id), publicApi.standings(id)])}>{([competition, fixture, standings]: [Competition, Fixture, Standings]) => <CompetitionContent competition={competition} fixture={fixture} standings={standings} />}</Load>; }
function CompetitionContent({ competition, fixture, standings }: { competition: Competition; fixture: Fixture; standings: Standings }) { const { setCompetition } = useOutletContext<Context>(); const location = useLocation(); useEffect(() => { setCompetition(competition); return () => setCompetition(undefined); }, [competition, setCompetition]); useEffect(() => { if (location.hash) requestAnimationFrame(() => document.getElementById(location.hash.slice(1))?.scrollIntoView({ block: 'start' })); }, [location.hash]); return <><header className="hero"><p>{competition.season.name} · {competition.division.name}</p><h1>{competition.name}</h1><span>{label(competition.status)}</span></header><section id="fixture"><h2>Fixture y resultados</h2>{fixture.phases.map(phase => <div key={phase.phaseId}><h3>{phase.name}</h3>{phase.rounds.map(round => <div key={round.roundNumber}><h4>Ronda {round.roundNumber}</h4>{round.matches.map(match => <MatchCard key={match.matchId} match={match} />)}</div>)}</div>)}</section><section id="standings"><h2>Posiciones</h2>{standings.tables.map(table => <StandingsTableView key={`${table.phaseId}-${table.phaseGroupId ?? 0}`} table={table} />)}</section><section id="playoffs"><h2>Playoffs</h2>{competition.phases.filter(phase => phase.playoffSeries.length).map(phase => <div key={phase.phaseId}><h3>{phase.name}</h3><Bracket series={phase.playoffSeries} /></div>)}</section></>; }

function MatchPage() { const id = Number(useParams().matchId); return <Load key={id} run={() => publicApi.match(id)}>{match => <MatchContent match={match} />}</Load>; }
function MatchContent({ match }: { match: MatchDetail }) { const { setCompetition } = useOutletContext<Context>(); useEffect(() => { setCompetition({ competitionId: match.competition.competitionId, name: match.competition.competitionName, season: { seasonId: match.competition.seasonId ?? match.competition.seasonYear, year: match.competition.seasonYear, name: String(match.competition.seasonYear) }, division: { divisionId: 0, name: match.competition.divisionName, levelOrder: 0, gender: match.competition.gender }, periodType: '', status: match.status }); return () => setCompetition(undefined); }, [match, setCompetition]); return <div className="public-match-page"><Link to={`/competitions/${match.competition.competitionId}`}>← {match.competition.competitionName}</Link><header className="match-context"><h1>{match.scope.phaseName}{match.scope.phaseGroupName ? ` · ${match.scope.phaseGroupName}` : ''}{match.scope.seriesName ? ` · ${match.scope.seriesName}` : ''}</h1><p>{match.competition.seasonYear} · {match.competition.divisionName}</p><small>{match.matchDate ? new Date(match.matchDate).toLocaleString() : 'Fecha a confirmar'} · {match.venue?.name ?? 'Sede a confirmar'}</small></header><PublicMatchLive match={match} /></div>; }

export default function App() { return <BrowserRouter><Routes><Route element={<PublicLayout />}><Route path="/" element={<Home />} /><Route path="/seasons/:seasonId" element={<SeasonHome />} /><Route path="/competitions" element={<Competitions />} /><Route path="/competitions/:competitionId" element={<CompetitionPage />} /><Route path="/matches/:matchId" element={<MatchPage />} /></Route></Routes></BrowserRouter>; }
