import{Link}from'react-router-dom';import type{FixtureMatch,PlayoffParticipant,PlayoffSeries,StandingsTable}from'../api/types';import{TeamLogo}from'./TeamLogo';export{TeamLogo}from'./TeamLogo';
export const label=(s:string)=>({Pending:'Pendiente',Ready:'Listo',Scheduled:'Programado',InProgress:'En juego',Suspended:'Suspendido',Finished:'Finalizado',Cancelled:'Cancelado'}[s]??s);
const fixtureDate=(date?:string)=>date?new Intl.DateTimeFormat('es-UY',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(date)):'Fecha a confirmar';
export function MatchCard({match}:{match:FixtureMatch}){
  const result=match.score?`${match.score.homeSets}–${match.score.awaySets}`:'—';
  return <Link className={`match match-${match.status.toLowerCase()}`} to={`/matches/${match.matchId}`} aria-label={`${match.homeTeam.teamName} contra ${match.awayTeam.teamName}, ${label(match.status)}`}>
    <div className="match-teams">
      <span className="match-team match-home"><TeamLogo team={match.homeTeam}/><b>{match.homeTeam.teamName}</b></span>
      <span className="match-versus">vs</span>
      <span className="match-team match-away"><b>{match.awayTeam.teamName}</b><TeamLogo team={match.awayTeam}/></span>
    </div>
    <div className="match-summary">
      <strong className="match-result" aria-label={`Resultado: ${result}`}>{result}</strong>
      <span className="match-status">{label(match.status)}</span>
      <small className="match-meta">{fixtureDate(match.matchDate)} <span aria-hidden="true">·</span> {match.venue?.name??'Sede a confirmar'}</small>
    </div>
  </Link>
}
export function StandingsTableView({table}:{table:StandingsTable}){return <section className="standings-table-section"><h2>{table.phaseGroupName??table.phaseName}</h2>{!table.isFinal&&<p className="note">Posiciones provisorias</p>}<div className="table-scroll"><table className="standings-table"><thead><tr><th>Pos</th><th>Equipo</th><th>PJ</th><th>PG</th><th>PP</th><th className="standing-secondary">Sets</th><th className="standing-secondary">Ratio sets</th><th className="standing-secondary">Puntos</th><th className="standing-secondary">Ratio pts</th><th>PT</th></tr></thead><tbody>{table.rows.map(r=><tr key={r.teamEntryId}><td>{r.position}{r.isTied?'=':''}</td><th>{r.teamName}</th><td>{r.played}</td><td>{r.won}</td><td>{r.lost}</td><td className="standing-secondary">{r.setsWon}/{r.setsLost}</td><td className="standing-secondary">{r.setRatio?.toFixed(3)??'—'}</td><td className="standing-secondary">{r.pointsWon}/{r.pointsLost}</td><td className="standing-secondary">{r.pointRatio?.toFixed(3)??'—'}</td><td><b>{r.tablePoints}</b></td></tr>)}</tbody></table></div></section>}
function SeriesParticipant({participant,wins,winner}:{participant:PlayoffParticipant;wins:number;winner:boolean}){const source=participant.source;return <div className={`series-participant${winner?' winner':''}`}>{participant.team?<><TeamLogo team={participant.team}/><b>{participant.team.teamName}</b></>:<span className="series-source">{source?`${source.displayName}${source.sourceSeriesCode?` (${source.sourceSeriesCode})`:''}`:'Por definir'}</span>}<strong aria-label={`Victorias de serie: ${wins}`}>{wins}</strong></div>}
type SeriesRelation={sourceCode:string;targetCode:string;kind:'winner'|'loser'};
function relations(series:PlayoffSeries[]):SeriesRelation[]{const codes=new Set(series.map(item=>item.code));return series.flatMap(target=>[target.team1,target.team2].flatMap<SeriesRelation>(participant=>{const source=participant.source;if(!source?.sourceSeriesCode||!codes.has(source.sourceSeriesCode))return [];if(source.sourceType==='SeriesWinner')return[{sourceCode:source.sourceSeriesCode,targetCode:target.code,kind:'winner'}];if(source.sourceType==='SeriesLoser')return[{sourceCode:source.sourceSeriesCode,targetCode:target.code,kind:'loser'}];return [];}));}
function SeriesCard({series,relations}:{series:PlayoffSeries;relations:SeriesRelation[]}){const inbound=relations.filter(relation=>relation.targetCode===series.code);return <article className={`series${inbound.length?' series-target':''}${inbound.some(relation=>relation.kind==='winner')?' series-target-winner':''}${inbound.some(relation=>relation.kind==='loser')?' series-target-loser':''}`} data-series-code={series.code}><header><div><b>{series.name}</b>{series.code!==series.name&&<small>{series.code}</small>}</div><span className={`series-status series-${series.status.toLowerCase()}`}>{label(series.status)}</span></header><SeriesParticipant participant={series.team1} wins={series.team1SeriesWins} winner={series.winnerTeamEntryId!==undefined&&series.winnerTeamEntryId===series.team1.team?.teamEntryId}/><SeriesParticipant participant={series.team2} wins={series.team2SeriesWins} winner={series.winnerTeamEntryId!==undefined&&series.winnerTeamEntryId===series.team2.team?.teamEntryId}/><small className="series-meta">Al mejor de {series.winsRequired} victoria{series.winsRequired===1?'':'s'}{series.team1InitialWins+series.team2InitialWins>0?` · Ventaja inicial: ${series.team1InitialWins}–${series.team2InitialWins}`:''}</small>{series.matches.length?<div className="series-matches">{series.matches.map(match=><MatchCard key={match.matchId} match={match}/>)}</div>:<p className="series-empty">Sin partidos materializados todavía.</p>}</article>}
export function Bracket({series}:{series:PlayoffSeries[]}){const layoutRelations=relations(series);const targets=new Set(layoutRelations.map(relation=>relation.targetCode));const sources=new Set(layoutRelations.map(relation=>relation.sourceCode));if(!layoutRelations.length)return <div className="bracket bracket-list">{series.map(item=><SeriesCard key={item.seriesId} series={item} relations={layoutRelations}/>)}</div>;return <div className="bracket bracket-layout"><div className="bracket-sources">{series.filter(item=>sources.has(item.code)).map(item=><SeriesCard key={item.seriesId} series={item} relations={layoutRelations}/>)}</div><div className="bracket-targets">{series.filter(item=>targets.has(item.code)).map(item=>{const inbound=layoutRelations.filter(relation=>relation.targetCode===item.code);return <div className="bracket-target" key={item.seriesId} data-relations={inbound.map(relation=>`${relation.kind}:${relation.sourceCode}`).join(',')}><div className="bracket-connectors" aria-hidden="true">{inbound.map(relation=><span key={`${relation.kind}-${relation.sourceCode}`} className={`bracket-connector bracket-connector-${relation.kind}`} />)}</div><SeriesCard series={item} relations={layoutRelations}/></div>;})}</div>{series.filter(item=>!sources.has(item.code)&&!targets.has(item.code)).map(item=><SeriesCard key={item.seriesId} series={item} relations={layoutRelations}/>)}</div>}
