using LigaVolley.Domain.Common;using LigaVolley.Domain.CompetitionRosters;using LigaVolley.Domain.Fixtures;using LigaVolley.Domain.MatchOfficials;using LigaVolley.Domain.TeamEntries;
namespace LigaVolley.Domain.MatchSheets;
public enum MatchSheetStatus{Open,InProgress,Suspended,Closed,Cancelled}public enum MatchSide{Home,Away}public enum MatchPlayerStatus{Available}public enum MatchTeamStaffStatus{Present}public enum MatchSheetSessionStatus{Active,Abandoned,Closed}public enum MatchSheetAuditType{MatchSheetOpened,MatchSheetTakenOver}
public sealed class MatchSheet
{
 private MatchSheet(){}public MatchSheet(Match match,DateTimeOffset now,Guid? uuid=null){Match=match??throw new DomainValidationException("Match is required.");MatchId=match.MatchId;SheetUuid=uuid??Guid.NewGuid();Status=MatchSheetStatus.Open;OpenedAt=now;}
 public int MatchSheetId{get;private set;}public Guid SheetUuid{get;private set;}public int MatchId{get;private set;}public Match Match{get;private set;}=null!;public MatchSheetStatus Status{get;private set;}public DateTimeOffset OpenedAt{get;private set;}public DateTimeOffset? StartedAt{get;private set;}public DateTimeOffset? EndedAt{get;private set;}public byte HomeSets{get;private set;}public byte AwaySets{get;private set;}public int? WinnerTeamEntryId{get;private set;}public bool TrackSubstitutions{get;private set;}=true;public bool TrackLiberoReplacements{get;private set;}=true;public List<MatchTeam> Teams{get;private set;}=[];public List<MatchSheetSession> Sessions{get;private set;}=[];public List<MatchSheetAudit> Audits{get;private set;}=[];public List<MatchSet> Sets{get;private set;}=[];public List<MatchEvent> Events{get;private set;}=[];
 public MatchTeam AddTeam(TeamEntry entry,CompetitionRoster roster,MatchSide side){if(Teams.Any(x=>x.Side==side))throw new DomainValidationException("Match side already exists.");var x=new MatchTeam(this,entry,roster,side);Teams.Add(x);return x;}
 public MatchSheetSession OpenSession(MatchOfficial scorer,string deviceId,DateTimeOffset now){if(Sessions.Any(x=>x.Status==MatchSheetSessionStatus.Active))throw new DomainValidationException("An active MatchSheet session already exists.");var x=new MatchSheetSession(this,scorer,deviceId,now);Sessions.Add(x);return x;}
 public void AuditOpened(MatchSheetSession session,Guid clientRequestId,DateTimeOffset now)=>Audits.Add(new MatchSheetAudit(this,session,clientRequestId,now));
 public MatchSheetSession TakeOver(string deviceId,Guid clientRequestId,DateTimeOffset now){if(Status==MatchSheetStatus.Closed)throw new DomainValidationException("A closed MatchSheet cannot be taken over.");var previous=Sessions.SingleOrDefault(x=>x.Status==MatchSheetSessionStatus.Active)??throw new DomainValidationException("An active MatchSheet session is required.");previous.Abandon(now);var next=OpenSession(previous.MatchOfficial,deviceId,now);Audits.Add(MatchSheetAudit.TakenOver(this,previous,next,clientRequestId,now));return next;}
 public void ConfigureTracking(bool substitutions,bool liberoReplacements){if(Status!=MatchSheetStatus.Open||Sets.Count>0)throw new DomainValidationException("Tracking can only be configured before preparing the first set.");TrackSubstitutions=substitutions;TrackLiberoReplacements=liberoReplacements;}
 public MatchSet PrepareSet(){if(Status!=MatchSheetStatus.Open&&Status!=MatchSheetStatus.InProgress)throw new DomainValidationException("MatchSheet cannot prepare a set in its current state.");if(Sets.Any(x=>x.Status!=MatchSetStatus.Finished))throw new DomainValidationException("Another set is active.");if(HomeSets==3||AwaySets==3)throw new DomainValidationException("Match is already decided.");var number=(byte)(Sets.Count+1);if(number>5)throw new DomainValidationException("Maximum sets reached.");var set=new MatchSet(this,number);Sets.Add(set);return set;}
 public void StartFirstSet(DateTimeOffset now){if(Status!=MatchSheetStatus.Open)throw new DomainValidationException("First set requires an Open MatchSheet.");Status=MatchSheetStatus.InProgress;StartedAt=now;}
 public void RecalculateSets(){HomeSets=(byte)Sets.Count(x=>x.Status==MatchSetStatus.Finished&&x.WinnerSide==MatchSide.Home);AwaySets=(byte)Sets.Count(x=>x.Status==MatchSetStatus.Finished&&x.WinnerSide==MatchSide.Away);}
 public MatchEvent AddEvent(Guid uuid,MatchEventType type,MatchSet? set,MatchSide? side,int? playerId,DateTimeOffset now,MatchEvent? related=null){var e=new MatchEvent(this,set,uuid,type,checked((long)Events.Count+1),side,playerId,now,related);Events.Add(e);return e;}
 public void Close(int winnerTeamEntryId,DateTimeOffset now){if(Status!=MatchSheetStatus.InProgress)throw new DomainValidationException("Only an InProgress MatchSheet can close.");Status=MatchSheetStatus.Closed;WinnerTeamEntryId=winnerTeamEntryId;EndedAt=now;Sessions.SingleOrDefault(x=>x.Status==MatchSheetSessionStatus.Active)?.Close(now);}
}
public sealed class MatchTeam{private MatchTeam(){}internal MatchTeam(MatchSheet sheet,TeamEntry entry,CompetitionRoster roster,MatchSide side){MatchSheet=sheet;TeamEntry=entry;CompetitionRoster=roster;Side=side;MatchTeamUuid=Guid.NewGuid();}public int MatchTeamId{get;private set;}public Guid MatchTeamUuid{get;private set;}public int MatchSheetId{get;private set;}public MatchSheet MatchSheet{get;private set;}=null!;public int TeamEntryId{get;private set;}public TeamEntry TeamEntry{get;private set;}=null!;public int CompetitionRosterId{get;private set;}public CompetitionRoster CompetitionRoster{get;private set;}=null!;public MatchSide Side{get;private set;}public List<MatchPlayer> Players{get;private set;}=[];public List<MatchTeamStaff> Staff{get;private set;}=[];public List<MatchLibero> Liberos{get;private set;}=[];public MatchPlayer AddPlayer(CompetitionRosterPlayer source,bool captain){var x=new MatchPlayer(this,source,captain);Players.Add(x);return x;}public void AddStaff(CompetitionRosterStaff source)=>Staff.Add(new MatchTeamStaff(this,source));public void AddLibero(MatchPlayer player,byte order)=>Liberos.Add(new MatchLibero(this,player,order));}
public sealed class MatchPlayer{private MatchPlayer(){}internal MatchPlayer(MatchTeam team,CompetitionRosterPlayer source,bool captain){MatchTeam=team;CompetitionRosterPlayer=source;JerseyNumber=source.JerseyNumber;IsMatchCaptain=captain;Status=MatchPlayerStatus.Available;MatchPlayerUuid=Guid.NewGuid();}public int MatchPlayerId{get;private set;}public Guid MatchPlayerUuid{get;private set;}public int MatchTeamId{get;private set;}public MatchTeam MatchTeam{get;private set;}=null!;public int CompetitionRosterPlayerId{get;private set;}public CompetitionRosterPlayer CompetitionRosterPlayer{get;private set;}=null!;public short? JerseyNumber{get;private set;}public bool IsMatchCaptain{get;private set;}public MatchPlayerStatus Status{get;private set;}}
public sealed class MatchTeamStaff{private MatchTeamStaff(){}internal MatchTeamStaff(MatchTeam team,CompetitionRosterStaff source){MatchTeam=team;CompetitionRosterStaff=source;Status=MatchTeamStaffStatus.Present;MatchTeamStaffUuid=Guid.NewGuid();}public int MatchTeamStaffId{get;private set;}public Guid MatchTeamStaffUuid{get;private set;}public int MatchTeamId{get;private set;}public MatchTeam MatchTeam{get;private set;}=null!;public int CompetitionRosterStaffId{get;private set;}public CompetitionRosterStaff CompetitionRosterStaff{get;private set;}=null!;public MatchTeamStaffStatus Status{get;private set;}}
public sealed class MatchLibero{private MatchLibero(){}internal MatchLibero(MatchTeam team,MatchPlayer player,byte order){if(order is not 1 and not 2)throw new DomainValidationException("LiberoOrder must be 1 or 2.");MatchTeam=team;MatchPlayer=player;LiberoOrder=order;MatchLiberoUuid=Guid.NewGuid();}public int MatchLiberoId{get;private set;}public Guid MatchLiberoUuid{get;private set;}public int MatchTeamId{get;private set;}public MatchTeam MatchTeam{get;private set;}=null!;public int MatchPlayerId{get;private set;}public MatchPlayer MatchPlayer{get;private set;}=null!;public byte LiberoOrder{get;private set;}}
public sealed class MatchSheetSession{private MatchSheetSession(){}internal MatchSheetSession(MatchSheet sheet,MatchOfficial scorer,string deviceId,DateTimeOffset now){var d=deviceId?.Trim();if(string.IsNullOrEmpty(d)||d.Length>100)throw new DomainValidationException("DeviceId is required and cannot exceed 100 characters.");MatchSheet=sheet;MatchOfficial=scorer;DeviceId=d;SessionUuid=Guid.NewGuid();Status=MatchSheetSessionStatus.Active;StartedAt=now;}public int MatchSheetSessionId{get;private set;}public Guid SessionUuid{get;private set;}public int MatchSheetId{get;private set;}public MatchSheet MatchSheet{get;private set;}=null!;public int MatchOfficialId{get;private set;}public MatchOfficial MatchOfficial{get;private set;}=null!;public string DeviceId{get;private set;}=null!;public MatchSheetSessionStatus Status{get;private set;}public long LastAcceptedSequence{get;private set;}public DateTimeOffset StartedAt{get;private set;}public DateTimeOffset? EndedAt{get;private set;}public void Accept(long sequence){if(Status!=MatchSheetSessionStatus.Active)throw new DomainValidationException("Only an active session accepts events.");if(sequence!=LastAcceptedSequence+1)throw new DomainValidationException("Session sequence must be contiguous.");LastAcceptedSequence=sequence;}public void Abandon(DateTimeOffset now){if(Status!=MatchSheetSessionStatus.Active)throw new DomainValidationException("Only an active session can be abandoned.");Status=MatchSheetSessionStatus.Abandoned;EndedAt=now;}public void Close(DateTimeOffset now){if(Status!=MatchSheetSessionStatus.Active)throw new DomainValidationException("Only an active session can be closed.");Status=MatchSheetSessionStatus.Closed;EndedAt=now;}}
public sealed class MatchSheetAudit{private MatchSheetAudit(){}internal MatchSheetAudit(MatchSheet sheet,MatchSheetSession session,Guid clientRequestId,DateTimeOffset now){MatchSheet=sheet;Session=session;ClientRequestId=clientRequestId;OccurredAt=now;AuditUuid=Guid.NewGuid();Type=MatchSheetAuditType.MatchSheetOpened;}private MatchSheetAudit(MatchSheet sheet,MatchSheetSession previous,MatchSheetSession next,Guid requestId,DateTimeOffset now){MatchSheet=sheet;Session=next;ClientRequestId=requestId;OccurredAt=now;AuditUuid=Guid.NewGuid();Type=MatchSheetAuditType.MatchSheetTakenOver;PreviousSessionUuid=previous.SessionUuid;PreviousDeviceId=previous.DeviceId;NewSessionUuid=next.SessionUuid;NewDeviceId=next.DeviceId;}internal static MatchSheetAudit TakenOver(MatchSheet sheet,MatchSheetSession previous,MatchSheetSession next,Guid requestId,DateTimeOffset now)=>new(sheet,previous,next,requestId,now);public int MatchSheetAuditId{get;private set;}public Guid AuditUuid{get;private set;}public int MatchSheetId{get;private set;}public MatchSheet MatchSheet{get;private set;}=null!;public int MatchSheetSessionId{get;private set;}public MatchSheetSession Session{get;private set;}=null!;public MatchSheetAuditType Type{get;private set;}public Guid ClientRequestId{get;private set;}public Guid? PreviousSessionUuid{get;private set;}public string? PreviousDeviceId{get;private set;}public Guid? NewSessionUuid{get;private set;}public string? NewDeviceId{get;private set;}public DateTimeOffset OccurredAt{get;private set;}}
