using LigaVolley.Application.Abstractions.Persistence; using LigaVolley.Application.Common; using LigaVolley.Domain.Common; using LigaVolley.Domain.People;
namespace LigaVolley.Application.People;
public sealed class PeopleService(IPeopleRepository repository,IUnitOfWork unit)
{
    public async Task<PagedResult<PersonSummaryDto>> ListPeopleAsync(string? query,string? documentType,string? documentNumber,DateOnly? birthDate,bool? active,int page,int pageSize,CancellationToken ct){Page(ref page,ref pageSize); var type=Norm(documentType)?.ToUpperInvariant();var number=Norm(documentNumber);if((type is null)!=(number is null))throw new RequestValidationException("person_document_incomplete","Document type and number must both be supplied for exact search.");var x=await repository.ListPeopleAsync(Norm(query),type,number,birthDate,active,page,pageSize,ct);return new(x.Items.Select(ToSummary).ToArray(),page,pageSize,x.Total);}
    public async Task<PersonDto> GetPersonAsync(int id,CancellationToken ct)=>ToDto(await Person(id,false,ct));
    public async Task<PersonDto> CreatePersonAsync(CreatePersonRequest r,CancellationToken ct){ValidatePerson(r.DocumentType,r.DocumentNumber,r.BirthDate,r.Email);await Unique(r.DocumentType,r.DocumentNumber,null,ct);var x=new Person(r.DocumentType,r.DocumentNumber,r.FirstName,r.LastName,r.BirthDate,r.Gender,r.Email,r.Phone);repository.Add(x);await unit.SaveChangesAsync(ct);return ToDto(x);}
    public async Task<PersonDto> UpdatePersonAsync(int id,UpdatePersonRequest r,CancellationToken ct){ValidatePerson(r.DocumentType,r.DocumentNumber,r.BirthDate,r.Email);var x=await Person(id,true,ct);await Unique(r.DocumentType,r.DocumentNumber,id,ct);x.Update(r.DocumentType,r.DocumentNumber,r.FirstName,r.LastName,r.BirthDate,r.Gender,r.Email,r.Phone);await unit.SaveChangesAsync(ct);return ToDto(x);}
    public async Task<PersonDto> SetPersonActiveAsync(int id,bool active,CancellationToken ct){var x=await Person(id,true,ct);x.SetActive(active);await unit.SaveChangesAsync(ct);return ToDto(x);}
    public async Task<IReadOnlyList<PersonAdditionalDocumentDto>> ListDocumentsAsync(int personId,CancellationToken ct)=>(await Person(personId,false,ct)).AdditionalDocuments.OrderByDescending(x=>x.ValidTo).ThenByDescending(x=>x.PersonAdditionalDocumentId).Select(ToDocument).ToArray();
    public async Task<PersonAdditionalDocumentDto> AddDocumentAsync(int personId,CreatePersonAdditionalDocumentRequest r,CancellationToken ct){ValidateDates(r.ValidFrom,r.ValidTo);var person=await Person(personId,true,ct);var x=new PersonAdditionalDocument(person,r.DocumentType,r.DocumentNumber,r.ValidFrom,r.ValidTo,r.Notes);repository.Add(x);await unit.SaveChangesAsync(ct);return ToDocument(x);}
    public async Task<PersonAdditionalDocumentDto> UpdateDocumentAsync(int personId,int id,UpdatePersonAdditionalDocumentRequest r,CancellationToken ct){ValidateDates(r.ValidFrom,r.ValidTo);await Person(personId,false,ct);var x=await repository.GetDocumentAsync(personId,id,true,ct)??throw new ResourceNotFoundException("PersonAdditionalDocument",id);x.Update(r.DocumentType,r.DocumentNumber,r.ValidFrom,r.ValidTo,r.Notes);await unit.SaveChangesAsync(ct);return ToDocument(x);}
    public async Task<PersonAdditionalDocumentDto> SetDocumentActiveAsync(int personId,int id,bool active,CancellationToken ct){await Person(personId,false,ct);var x=await repository.GetDocumentAsync(personId,id,true,ct)??throw new ResourceNotFoundException("PersonAdditionalDocument",id);x.SetActive(active);await unit.SaveChangesAsync(ct);return ToDocument(x);}
    public async Task<PagedResult<PlayerDto>> ListPlayersAsync(string? q,bool? active,int page,int size,CancellationToken ct){Page(ref page,ref size);var x=await repository.ListPlayersAsync(Norm(q),active,page,size,ct);return new(x.Items.Select(ToPlayer).ToArray(),page,size,x.Total);}
    public async Task<PlayerDto> GetPlayerAsync(int id,CancellationToken ct)=>ToPlayer(await repository.GetPlayerAsync(id,false,ct)??throw new ResourceNotFoundException("Player",id));
    public async Task<PlayerDto> CreatePlayerAsync(int personId,CancellationToken ct){var p=await Person(personId,true,ct);if(await repository.PlayerExistsAsync(personId,ct))throw Conflict("player_profile_already_exists","Player profile already exists.");var x=new Player(p);repository.Add(x);await unit.SaveChangesAsync(ct);return ToPlayer(x);}
    public async Task<PlayerDto> SetPlayerActiveAsync(int id,bool active,CancellationToken ct){var x=await repository.GetPlayerAsync(id,true,ct)??throw new ResourceNotFoundException("Player",id);x.SetActive(active);await unit.SaveChangesAsync(ct);return ToPlayer(x);}
    public async Task<PagedResult<CoachDto>> ListCoachesAsync(string? q,bool? active,int page,int size,CancellationToken ct){Page(ref page,ref size);var x=await repository.ListCoachesAsync(Norm(q),active,page,size,ct);return new(x.Items.Select(ToCoach).ToArray(),page,size,x.Total);}
    public async Task<CoachDto> GetCoachAsync(int id,CancellationToken ct)=>ToCoach(await repository.GetCoachAsync(id,false,ct)??throw new ResourceNotFoundException("Coach",id));
    public async Task<CoachDto> CreateCoachAsync(int personId,CancellationToken ct){var p=await Person(personId,true,ct);if(await repository.CoachExistsAsync(personId,ct))throw Conflict("coach_profile_already_exists","Coach profile already exists.");var x=new Coach(p);repository.Add(x);await unit.SaveChangesAsync(ct);return ToCoach(x);}
    public async Task<CoachDto> SetCoachActiveAsync(int id,bool active,CancellationToken ct){var x=await repository.GetCoachAsync(id,true,ct)??throw new ResourceNotFoundException("Coach",id);x.SetActive(active);await unit.SaveChangesAsync(ct);return ToCoach(x);}
    public async Task<PagedResult<RefereeDto>> ListRefereesAsync(string? q,bool? active,int page,int size,CancellationToken ct){Page(ref page,ref size);var x=await repository.ListRefereesAsync(Norm(q),active,page,size,ct);return new(x.Items.Select(ToReferee).ToArray(),page,size,x.Total);}
    public async Task<RefereeDto> GetRefereeAsync(int id,CancellationToken ct)=>ToReferee(await repository.GetRefereeAsync(id,false,ct)??throw new ResourceNotFoundException("Referee",id));
    public async Task<RefereeDto> CreateRefereeAsync(int personId,CancellationToken ct){var p=await Person(personId,true,ct);if(await repository.RefereeExistsAsync(personId,ct))throw Conflict("referee_profile_already_exists","Referee profile already exists.");var x=new Referee(p);repository.Add(x);await unit.SaveChangesAsync(ct);return ToReferee(x);}
    public async Task<RefereeDto> SetRefereeActiveAsync(int id,bool active,CancellationToken ct){var x=await repository.GetRefereeAsync(id,true,ct)??throw new ResourceNotFoundException("Referee",id);x.SetActive(active);await unit.SaveChangesAsync(ct);return ToReferee(x);}
    private async Task<Person> Person(int id,bool tracking,CancellationToken ct)=>await repository.GetPersonAsync(id,tracking,ct)??throw new ResourceNotFoundException("Person",id);
    private async Task Unique(string? t,string? n,int? id,CancellationToken ct){t=Norm(t)?.ToUpperInvariant();n=Norm(n);if(t is not null&&await repository.DocumentExistsAsync(t,n!,id,ct)){var existing=(await repository.ListPeopleAsync(null,t,n,null,null,1,1,ct)).Items.First();throw Conflict("person_document_already_exists","A person with this document already exists.",new(){["existingPersonId"]=existing.PersonId});}}
    private static void ValidatePerson(string? t,string? n,DateOnly? birth,string? email){if((Norm(t)is null)!=(Norm(n)is null))throw new RequestValidationException("person_document_incomplete","Document type and number must both be present or both be null.");if(birth>DateOnly.FromDateTime(DateTime.UtcNow))throw new RequestValidationException("person_birth_date_invalid","Birth date cannot be in the future.");if(Norm(email)is { } e&&!System.Net.Mail.MailAddress.TryCreate(e,out _))throw new RequestValidationException("person_email_invalid","Email is invalid.");}
    private static void ValidateDates(DateOnly? from,DateOnly? to){if(from>to)throw new RequestValidationException("person_additional_document_invalid_dates","Valid from cannot be after valid to.");}
    private static void Page(ref int p,ref int s){if(p==0)p=1;if(s==0)s=25;if(p<1||s<1||s>100)throw new RequestValidationException("invalid_pagination","Page must be at least 1 and pageSize between 1 and 100.");}
    private static ResourceConflictException Conflict(string c,string m,Dictionary<string,object?>? e=null)=>new(c,m){Extensions=e??new()}; private static string? Norm(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
    private static PersonSummaryDto ToSummary(Person x)=>new(x.PersonId,x.FirstName,x.LastName,x.BirthDate,x.DocumentType,x.DocumentNumber,x.Active);
    private static PersonAdditionalDocumentDto ToDocument(PersonAdditionalDocument x)=>new(x.PersonAdditionalDocumentId,x.DocumentType,x.DocumentNumber,x.ValidFrom,x.ValidTo,x.Active,x.Notes);
    private static PersonDto ToDto(Person x)=>new(x.PersonId,x.DocumentType,x.DocumentNumber,x.FirstName,x.LastName,x.BirthDate,x.Gender,x.Email,x.Phone,x.Active,new(x.Player is null?null:new(x.Player.PlayerId,x.Player.Active),x.Coach is null?null:new(x.Coach.CoachId,x.Coach.Active),x.Referee is null?null:new(x.Referee.RefereeId,x.Referee.Active)),x.AdditionalDocuments.Select(ToDocument).ToArray());
    private static RelevantDocumentDto? Relevant(Person p,PersonAdditionalDocumentType type)=>p.AdditionalDocuments.Where(x=>x.DocumentType==type&&x.Active).OrderByDescending(x=>x.ValidTo).ThenByDescending(x=>x.ValidFrom).ThenByDescending(x=>x.PersonAdditionalDocumentId).Select(x=>new RelevantDocumentDto(x.PersonAdditionalDocumentId,x.DocumentNumber,x.ValidFrom,x.ValidTo,x.Active)).FirstOrDefault();
    private static HealthCardDto Health(Person p)=>HealthCardEvaluator.Evaluate(p);
    private static PlayerDto ToPlayer(Player x)=>new(x.PlayerId,x.PersonId,x.Person.FirstName,x.Person.LastName,x.Person.BirthDate,x.Person.Gender,x.Person.Active,x.Active,Health(x.Person),Relevant(x.Person,PersonAdditionalDocumentType.LeagueCard));
    private static CoachDto ToCoach(Coach x)=>new(x.CoachId,x.PersonId,x.Person.FirstName,x.Person.LastName,x.Person.BirthDate,x.Person.Gender,x.Person.Active,x.Active);
    private static RefereeDto ToReferee(Referee x)=>new(x.RefereeId,x.PersonId,x.Person.FirstName,x.Person.LastName,x.Person.BirthDate,x.Person.Gender,x.Person.Active,x.Active,Health(x.Person),Relevant(x.Person,PersonAdditionalDocumentType.LeagueCard));
}
