using LigaVolley.Domain.MatchSheets;
using LigaVolley.Domain.Common;using LigaVolley.Domain.MatchOfficials;using LigaVolley.Domain.People;using LigaVolley.Domain.Fixtures;using LigaVolley.Domain.CompetitionFormats;using LigaVolley.Domain.Competitions;using LigaVolley.Domain.Seasons;using LigaVolley.Domain.Divisions;using LigaVolley.Domain.Teams;using LigaVolley.Domain.TeamEntries;
namespace LigaVolley.Domain.Tests;
public sealed class MatchSheetTests
{
 [Fact]public void Match_sheet_status_contract_contains_only_v1_states()=>Assert.Equal([MatchSheetStatus.Open,MatchSheetStatus.InProgress,MatchSheetStatus.Suspended,MatchSheetStatus.Closed,MatchSheetStatus.Cancelled],Enum.GetValues<MatchSheetStatus>());
 [Fact]public void Session_sequence_is_contiguous_and_non_active_session_rejects_events(){var (sheet,official)=Subject();var session=sheet.OpenSession(official,"device-a",DateTimeOffset.UtcNow);session.Accept(1);session.Accept(2);Assert.Equal(2,session.LastAcceptedSequence);Assert.Throws<DomainValidationException>(()=>session.Accept(2));session.Abandon(DateTimeOffset.UtcNow);Assert.Equal(MatchSheetSessionStatus.Abandoned,session.Status);Assert.Throws<DomainValidationException>(()=>session.Accept(3));}
 [Fact]public void Takeover_abandons_previous_and_creates_only_one_active_session_at_zero(){var (sheet,official)=Subject();var previous=sheet.OpenSession(official,"device-a",DateTimeOffset.UtcNow);previous.Accept(1);var next=sheet.TakeOver("device-b",Guid.NewGuid(),DateTimeOffset.UtcNow);Assert.Equal(MatchSheetSessionStatus.Abandoned,previous.Status);Assert.Equal(MatchSheetSessionStatus.Active,next.Status);Assert.Equal(0,next.LastAcceptedSequence);Assert.Single(sheet.Sessions.Where(x=>x.Status==MatchSheetSessionStatus.Active));var audit=Assert.Single(sheet.Audits);Assert.Equal(MatchSheetAuditType.MatchSheetTakenOver,audit.Type);Assert.Equal(previous.SessionUuid,audit.PreviousSessionUuid);Assert.Equal(next.SessionUuid,audit.NewSessionUuid);}
 [Fact]public void A_second_active_session_is_rejected(){var (sheet,official)=Subject();sheet.OpenSession(official,"device-a",DateTimeOffset.UtcNow);Assert.Throws<DomainValidationException>(()=>sheet.OpenSession(official,"device-b",DateTimeOffset.UtcNow));}
 private static (MatchSheet,MatchOfficial) Subject(){var f=new CompetitionFormat("MS","Sheet",null,2,2);f.Phases.Add(new FormatPhase("R","Regular",PhaseType.RoundRobin,PhaseRole.Regular,1,1,FixtureMode.BalancedRandom));var c=new Competition("C",new Season(2026,"2026",null,null),new Division("D",1,Gender.Female),f,CompetitionPeriodType.Annual,null,null);var a=new TeamEntry(c,new Team("A",Gender.Female,null),null);var b=new TeamEntry(c,new Team("B",Gender.Female,null),null);var match=new Match(c,c.Phases[0],null,a,b,1,1);var official=new MatchOfficial(match,new Referee(new Person(null,null,"Ana","Scorer",null,null,null,null)),MatchOfficialRole.Scorer);return(new MatchSheet(match,DateTimeOffset.UtcNow),official);}
}
