import{FormEvent,useEffect,useMemo,useState}from'react';
import{Link,useBlocker,useNavigate,useParams}from'react-router-dom';
import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';
import{adminApi}from'./api/adminApiClient';
import{EmptyState,LoadingState,ProblemDetailsAlert}from'./components/feedback';
import{PageHeader}from'./components/layout';
import{FormatDefinitionEditor,type Definition}from'./competitionFormatEditorSections';
export type FormatDto={competitionFormatId:number;code:string;name:string;description?:string;minTeams:number;maxTeams:number;active:boolean;used:boolean;isStructurallyLocked:boolean;usedByDraftCompetitionCount:number;usedByOperationalCompetitionCount:number;definition:Definition};
export type ValidationDto={isValid:boolean;errors:Issue[];warnings:Issue[];teamCounts:{teamCount:number;isValid:boolean;errorCount:number;issues:Issue[]}[]};type Issue={code:string;path:string;message:string;severity:string};
export const initialDefinition:Definition={phases:[{code:'REGULAR',name:'Regular',phaseType:'RoundRobin',phaseRole:'Regular',sequence:1,rounds:1,fixtureMode:'BalancedRandom',groups:[],series:[]}],qualificationRules:[],scoringRules:[{winnerSets:3,loserSets:0,winnerTablePoints:3,loserTablePoints:0},{winnerSets:3,loserSets:1,winnerTablePoints:3,loserTablePoints:0},{winnerSets:3,loserSets:2,winnerTablePoints:2,loserTablePoints:1}],tiebreakRules:[{sequence:1,criterion:'TablePoints',sortDirection:'Desc'}],movementRules:[]};
const snapshot=(x:{code:string;name:string;description?:string|null;minTeams:number;maxTeams:number;definition:Definition})=>JSON.stringify({...x,description:x.description||null});
export function CompetitionFormatsPage(){const formats=useQuery({queryKey:['competition-formats'],queryFn:()=>adminApi.get<FormatDto[]>('/competition-formats')});return <section><PageHeader title="Formatos de competición"><Link className="button" to="/admin/competition-formats/new">+ Nuevo formato</Link></PageHeader>{formats.isLoading?<LoadingState/>:formats.error?<ProblemDetailsAlert error={formats.error}/>:!formats.data?.length?<EmptyState/>:<table><thead><tr><th>Formato</th><th>Equipos</th><th>Estado</th><th>Uso</th></tr></thead><tbody>{formats.data.map(x=><tr key={x.competitionFormatId}><td><Link to={`/admin/competition-formats/${x.competitionFormatId}`}>{x.name}</Link><small> {x.code}</small></td><td>{x.minTeams}–{x.maxTeams}</td><td>{x.active?'Activo':'Inactivo'}</td><td>{x.isStructurallyLocked?'Estructura bloqueada':x.used?'Usado en borradores':'Sin uso'}</td></tr>)}</tbody></table>}</section>}
export function CompetitionFormatEditorPage(){const{id}=useParams(),creating=id==='new',nav=useNavigate(),qc=useQueryClient(),query=useQuery({queryKey:['competition-format',id],queryFn:()=>adminApi.get<FormatDto>(`/competition-formats/${id}`),enabled:!creating});const[code,setCode]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[minTeams,setMin]=useState(4),[maxTeams,setMax]=useState(8),[definition,setDefinition]=useState<Definition>(initialDefinition),[base,setBase]=useState(''),[validation,setValidation]=useState<ValidationDto>();const currentSnapshot=useMemo(()=>snapshot({code,name,description,minTeams,maxTeams,definition}),[code,name,description,minTeams,maxTeams,definition]),dirty=base!==''&&currentSnapshot!==base;
 useEffect(()=>{if(query.data){const x=query.data;setCode(x.code);setName(x.name);setDescription(x.description??'');setMin(x.minTeams);setMax(x.maxTeams);setDefinition(x.definition);setBase(snapshot(x))}else if(creating&&base==='')setBase(snapshot({code:'',name:'',description:null,minTeams:4,maxTeams:8,definition:initialDefinition}))},[query.data,creating,base]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard)},[dirty]);const blocker=useBlocker(dirty);useEffect(()=>{if(blocker.state==='blocked'){if(confirm('Hay cambios sin guardar. ¿Querés salir y perderlos?'))blocker.proceed();else blocker.reset()}},[blocker]);
 const body={code,name,description:description||null,minTeams,maxTeams,definition};const validate=useMutation({mutationFn:()=>adminApi.post<ValidationDto>('/competition-formats/validate',body),onSuccess:setValidation});const save=useMutation({mutationFn:()=>creating?adminApi.post<FormatDto>('/competition-formats',body):adminApi.put<FormatDto>(`/competition-formats/${id}`,body),onSuccess:x=>{setBase(snapshot(x));void qc.invalidateQueries({queryKey:['competition-formats']});if(creating)nav(`/admin/competition-formats/${x.competitionFormatId}`,{replace:true})}});const active=useMutation({mutationFn:(value:boolean)=>adminApi.patch<FormatDto>(`/competition-formats/${id}/active`,{active:value}),onSuccess:()=>{void query.refetch();void qc.invalidateQueries({queryKey:['competition-formats']})}});
 if(!creating&&query.isLoading)return <section><LoadingState/></section>;if(query.error)return <section><ProblemDetailsAlert error={query.error}/></section>;const current=query.data,locked=current?.isStructurallyLocked??false;
 function submit(e:FormEvent){e.preventDefault();validate.mutate(undefined,{onSuccess:r=>{if(!r.isValid)return;if(r.warnings.length&&!confirm(`El formato es válido pero tiene ${r.warnings.length} advertencias. ¿Guardar de todas formas?`))return;save.mutate()}})}async function clone(){const nextCode=prompt('Nuevo Code');if(!nextCode)return;const nextName=prompt('Nuevo Name');if(!nextName)return;const copy=await adminApi.post<FormatDto>(`/competition-formats/${id}/clone`,{code:nextCode,name:nextName,description});nav(`/admin/competition-formats/${copy.competitionFormatId}`)}
 return <section><PageHeader title={creating?'Nuevo formato':name}><span>{dirty&&<strong>Hay cambios sin guardar</strong>} {!creating&&<button onClick={clone}>Clonar</button>}</span></PageHeader>{locked&&<div className="alert"><strong>ESTRUCTURA BLOQUEADA</strong><p>Este formato ya fue utilizado por una competición operativa. Su estructura no puede modificarse.</p><button onClick={clone}>Clonar para modificar</button></div>}{!locked&&current&&current.usedByDraftCompetitionCount>0&&dirty&&<div className="warning">Este formato es utilizado por {current.usedByDraftCompetitionCount} competiciones en borrador. Los cambios no modificarán sus estructuras ya instanciadas.</div>}<form onSubmit={submit}><div className="card form-grid"><label>Code<input required value={code} disabled={locked} onChange={e=>setCode(e.target.value)}/></label><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Descripción<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Mínimo de equipos<input type="number" min="2" disabled={locked} value={minTeams} onChange={e=>setMin(Number(e.target.value))}/></label><label>Máximo de equipos<input type="number" min={minTeams} disabled={locked} value={maxTeams} onChange={e=>setMax(Number(e.target.value))}/></label></div><div className="card"><h3>Preview deportivo</h3>{definition.phases.map((p,i)=><p key={`${p.code}-${i}`}><strong>{i+1}. {p.name}</strong> · {p.phaseType} · {p.groups?.length??0} grupos · {p.series?.length??0} series</p>)}</div><FormatDefinitionEditor value={definition} onChange={setDefinition} readOnly={locked}/><ValidationPanel value={validation}/>{(validate.error||save.error||active.error)&&<ProblemDetailsAlert error={validate.error||save.error||active.error}/>}<div className="editor-actions"><button type="button" onClick={()=>validate.mutate()}>Validar</button><button type="submit" disabled={!dirty}>Guardar cambios</button>{!creating&&<button type="button" onClick={()=>{if(current?.active){if(confirm('Las competiciones existentes no se modificarán. El formato dejará de estar disponible para crear nuevas competiciones.'))active.mutate(false)}else active.mutate(true)}}>{current?.active?'Desactivar':'Activar formato'}</button>}</div></form></section>}
function ValidationPanel({value}:{value?:ValidationDto}){return <div className="card" id="validation"><h3>Validación</h3>{!value?<p>Validá para comprobar el agregado y cada cantidad de equipos.</p>:<><strong>{value.isValid?'Formato válido':`${value.errors.length} errores · ${value.warnings.length} advertencias`}</strong>{[...value.errors,...value.warnings].map(x=><p className={x.severity==='Warning'?'warning':'blocker'} key={x.code+x.path}>{x.message}<br/><small>{x.code} · {x.path}</small> <a href={`#${x.path.split('.')[1]??'validation'}`}>Ir al problema</a></p>)}<div className="team-count-validation">{value.teamCounts.map(x=><span className={x.isValid?'ok':'blocker'} key={x.teamCount}>{x.teamCount} equipos {x.isValid?'✓':`✕ ${x.errorCount} errores`}</span>)}</div></>}</div>}
