export type Status='Draft'|'Pending'|'Scheduled'|'InProgress'|'Suspended'|'Finished'|'Cancelled'|'Ready';
export interface Season{seasonId:number;year:number;name:string} export interface Division{divisionId:number;name:string;levelOrder:number;gender:string}
export interface CompetitionSummary{competitionId:number;name:string;season:Season;division:Division;periodType:string;startDate?:string;endDate?:string;status:Status}
export interface Team{teamEntryId:number;teamName:string;clubLogoUrl?:string} export interface Venue{venueId:number;name:string} export interface SetResult{setNumber:number;homePoints:number;awayPoints:number} export interface Score{homeSets:number;awaySets:number;sets:SetResult[]}
export interface FixtureMatch{matchId:number;matchNumber?:number;homeTeam:Team;awayTeam:Team;matchDate?:string;venue?:Venue;status:Status;score?:Score}
export interface Round{roundNumber:number;matches:FixtureMatch[]} export interface FixtureGroup{phaseGroupId:number;code:string;name:string;groupRole:string;sequence:number;rounds:Round[]} export interface FixtureSeries{seriesId:number;code:string;name:string;sequence:number;status:Status;team1?:Team;team2?:Team;team1InitialWins:number;team2InitialWins:number;team1Wins:number;team2Wins:number;winsRequired:number;winnerTeamEntryId?:number;matches:FixtureMatch[]}
export interface FixturePhase{phaseId:number;code:string;name:string;phaseType:string;phaseRole:string;sequence:number;rounds:Round[];groups:FixtureGroup[];series:FixtureSeries[]} export interface Fixture{competitionId:number;competitionName:string;phases:FixturePhase[]}
export interface Standing{position:number;teamEntryId:number;teamName:string;played:number;won:number;lost:number;setsWon:number;setsLost:number;setRatio?:number;pointsWon:number;pointsLost:number;pointRatio?:number;tablePoints:number;isTied:boolean} export interface StandingsTable{phaseId:number;phaseName:string;phaseSequence:number;phaseGroupId?:number;phaseGroupName?:string;phaseGroupSequence?:number;isFinal:boolean;rows:Standing[]} export interface Standings{competitionId:number;competitionName:string;tables:StandingsTable[]}
export interface PlayoffParticipant{side:number;team?:Team;source?:{sourceType:string;sourceSeriesCode?:string;displayName:string}} export interface PlayoffSeries{seriesId:number;code:string;name:string;sequence:number;status:Status;team1:PlayoffParticipant;team2:PlayoffParticipant;team1InitialWins:number;team2InitialWins:number;team1RealWins:number;team2RealWins:number;team1SeriesWins:number;team2SeriesWins:number;winsRequired:number;winnerTeamEntryId?:number;matches:FixtureMatch[]} export interface Competition extends CompetitionSummary{teams:{teamEntryId:number;teamId:number;teamName:string}[];phases:{phaseId:number;code:string;name:string;phaseType:string;phaseRole:string;sequence:number;groups:{phaseGroupId:number;name:string}[];playoffSeries:PlayoffSeries[]}[]}
export interface MatchDetail{matchId:number;competition:{competitionId:number;competitionName:string;seasonYear:number;divisionName:string;gender:string};scope:{phaseName:string;phaseGroupName?:string;seriesName?:string};homeTeam:Team;awayTeam:Team;matchDate?:string;venue?:Venue;status:Status;roundNumber?:number;matchNumber?:number;result?:Score&{winnerTeamEntryId:number};liveAvailable:boolean}
export interface Court{positions:{position:number;player:{jerseyNumber:string;displayName:string;isLibero:boolean}}[]} export interface Live{matchId:number;status:Status;home:Team&{setsWon:number};away:Team&{setsWon:number};currentSetNumber?:number;sets:(SetResult&{status:Status;winnerSide?:string})[];servingSide?:'Home'|'Away'|null;servingPlayer:{jerseyNumber:number;displayName:string}|null;homeCourt?:Court;awayCourt?:Court;lastUpdatedAt?:string|null;serverTime:string}
