using LigaVolley.Application.Abstractions.Persistence;using LigaVolley.Application.Common;using LigaVolley.Application.People;using LigaVolley.Domain.Fixtures;using LigaVolley.Domain.MatchOfficials;
namespace LigaVolley.Application.MatchOfficials;
public sealed class MatchOfficialService(IMatchOfficialRepository repo,IFixtureRepository matches,IPeopleRepository people,IUnitOfWork unit)
{
 public async Task<IReadOnlyList<MatchOfficialDto>> ListAsync(int id,CancellationToken ct){await Match(id,ct);return Map(await repo.ListAsync(id,false,ct));}
 public async Task<MatchOfficialDto> AddAsync(int id,AddMatchOfficialRequest q,CancellationToken ct)=>await Change(id,ct,async list=>{EnsureAdmin(await Match(id,ct));EnsureUnique(list,q.Role,q.RefereeId,null);var r=await Ref(q.RefereeId,ct);var x=new MatchOfficial(await Match(id,ct),r,q.Role);repo.Add(x);return x;});
 public async Task<MatchOfficialDto> UpdateAsync(int id,int oid,UpdateMatchOfficialRequest q,CancellationToken ct)=>await Change(id,ct,async list=>{EnsureAdmin(await Match(id,ct));var x=await RequiredOfficial(id,oid,list,ct);EnsureUnique(list,q.Role,q.RefereeId,x);x.Update(await Ref(q.RefereeId,ct),q.Role);return x;});
 public async Task DeleteAsync(int id,int oid,CancellationToken ct){await Change(id,ct,async list=>{EnsureAdmin(await Match(id,ct));var x=await RequiredOfficial(id,oid,list,ct);repo.Remove(x);return x;});}
 public async Task<MatchOfficialDto> ReplaceAsync(int id,MatchOfficialRole role,ReplaceMatchOfficialRequest q,CancellationToken ct)=>await Change(id,ct,async list=>{var m=await Match(id,ct);MatchOfficialAssignmentValidator.EnsureScorerReplacementAllowed(m.Status);var x=list.SingleOrDefault(x=>x.Role==role)??throw new ResourceNotFoundException("MatchOfficial",role);EnsureUnique(list,role,q.RefereeId,x);x.Update(await Ref(q.RefereeId,ct),role);return x;});
 private async Task<MatchOfficialDto> Change(int id,CancellationToken ct,Func<List<MatchOfficial>,Task<MatchOfficial>> f){await using var tx=await unit.BeginSerializableTransactionAsync(ct);await repo.AcquireMatchLockAsync(id,ct);var list=(await repo.ListAsync(id,true,ct)).ToList();var x=await f(list);await unit.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map([x])[0];}
 private async Task<Match> Match(int id,CancellationToken ct)=>await matches.GetMatchAsync(id,true,ct)??throw new ResourceNotFoundException("Match",id);private async Task<Domain.People.Referee> Ref(int id,CancellationToken ct)=>await people.GetRefereeAsync(id,true,ct)??throw new ResourceNotFoundException("Referee",id);
 private async Task<MatchOfficial> RequiredOfficial(int matchId,int id,List<MatchOfficial> list,CancellationToken ct){var found=list.SingleOrDefault(x=>x.MatchOfficialId==id);if(found is not null)return found;var other=await repo.GetByIdAsync(id,ct);if(other is not null)throw Conflict("match_official_match_mismatch","MatchOfficial does not belong to Match.");throw new ResourceNotFoundException("MatchOfficial",id);}
 private static void EnsureAdmin(Match m)=>MatchOfficialAssignmentValidator.EnsureAdminEditable(m.Status);private static void EnsureUnique(IEnumerable<MatchOfficial> l,MatchOfficialRole role,int rid,MatchOfficial? self)=>MatchOfficialAssignmentValidator.EnsureUnique(l,role,rid,self);
 private static ResourceConflictException Conflict(string c,string m)=>new(c,m);private static IReadOnlyList<MatchOfficialDto> Map(IEnumerable<MatchOfficial> xs)=>xs.OrderBy(x=>x.Role).Select(x=>new MatchOfficialDto(x.MatchOfficialId,x.MatchId,x.RefereeId,x.Referee.PersonId,x.Referee.Person.FirstName,x.Referee.Person.LastName,x.Role,HealthCardEvaluator.Evaluate(x.Referee.Person).Status)).ToArray();
}
