using LigaVolley.Application.Abstractions.Persistence;
using LigaVolley.Application.Common;
using LigaVolley.Application.People;
using LigaVolley.Application.Matches;
using LigaVolley.Domain.CompetitionRosters;
using LigaVolley.Domain.Fixtures;
using LigaVolley.Domain.MatchOfficials;
using LigaVolley.Domain.MatchSheets;
namespace LigaVolley.Application.MatchSheets;
public sealed class MatchSheetService(IFixtureRepository matches, ICompetitionRosterRepository rosters, IMatchOfficialRepository officials, IMatchSheetRepository sheets, IUnitOfWork unit, MatchOpeningPrerequisiteEvaluator prerequisites)
{
    public async Task<OpenMatchContextDto> GetOpenContextAsync(int matchId, CancellationToken ct) { var match = await RequiredMatch(matchId, false, ct); var home = await RequiredRoster(match.HomeTeamEntryId, "home", false, ct); var away = await RequiredRoster(match.AwayTeamEntryId, "away", false, ct); var os = await officials.ListAsync(matchId, false, ct); var existing = await sheets.GetAsync(matchId, false, ct); var warnings = new List<string>(); if (match.Status != MatchStatus.Scheduled) warnings.Add("Match is not Scheduled."); if (home.Status != CompetitionRosterStatus.Active) warnings.Add("Home roster is not Active."); if (away.Status != CompetitionRosterStatus.Active) warnings.Add("Away roster is not Active."); foreach (var role in Enum.GetValues<MatchOfficialRole>()) if (os.All(x => x.Role != role)) warnings.Add($"{role} is not assigned."); return new(ToMatch(match), ToCompetition(match), ToOpenTeam(home), ToOpenTeam(away), os.Select(ToOfficial).OrderBy(x => x.Role).ToArray(), warnings, existing is null ? null : Summary(existing)); }
    public async Task<OpenMatchSheetResponse> OpenAsync(int matchId, OpenMatchSheetRequest request, CancellationToken ct) { if (request.ClientRequestId == Guid.Empty) throw Invalid("invalid_client_request_id", "ClientRequestId is required."); if (request.Home is null || request.Away is null) throw Invalid("invalid_match_player_selection", "Home and Away selections are required."); await using var tx = await unit.BeginSerializableTransactionAsync(ct); await sheets.AcquireMatchLockAsync(matchId, ct); var existing = await sheets.GetAsync(matchId, true, ct); if (existing is not null) { var opening = existing.Audits.SingleOrDefault(x => x.Type == MatchSheetAuditType.MatchSheetOpened && x.ClientRequestId == request.ClientRequestId); if (opening is not null && !SameOpening(existing, request)) throw Conflict("match_sheet_open_idempotency_conflict", "ClientRequestId was already used with different jersey or captain selections."); var currentOfficials = await officials.ListAsync(matchId, false, ct); await tx.CommitAsync(ct); return new(true, Snapshot(existing, currentOfficials)); } var match = await RequiredMatch(matchId, true, ct); if (!match.HomeTeamEntryId.HasValue || !match.AwayTeamEntryId.HasValue) throw Conflict("match_participants_not_resolved", "Match participants are not resolved."); var home = await rosters.GetAsync(match.HomeTeamEntryId.Value, true, ct); var away = await rosters.GetAsync(match.AwayTeamEntryId.Value, true, ct); var os = await officials.ListAsync(matchId, true, ct); var evaluation = prerequisites.Evaluate(match, home, away, os, null); if (!evaluation.Ready) throw OpeningConflict(evaluation.Blockers[0]); var scorer = os.Single(x => x.Role == MatchOfficialRole.Scorer); var now = DateTimeOffset.UtcNow; var sheet = new MatchSheet(match, now); sheet.ConfigureTracking(request.TrackSubstitutions, request.TrackLiberoReplacements); var ht = sheet.AddTeam(match.HomeTeamEntry!, home!, MatchSide.Home); var at = sheet.AddTeam(match.AwayTeamEntry!, away!, MatchSide.Away); Materialize(ht, home!, request.Home, "home"); Materialize(at, away!, request.Away, "away"); var session = sheet.OpenSession(scorer, request.DeviceId, now); sheet.AuditOpened(session, request.ClientRequestId, now); sheets.Add(sheet); await unit.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(false, Snapshot(sheet, os)); }
    public async Task<MatchSheetSnapshotDto> GetSheetAsync(int matchId, CancellationToken ct) { var sheet = await sheets.GetAsync(matchId, false, ct) ?? throw new ResourceNotFoundException("MatchSheet", matchId); return Snapshot(sheet, await officials.ListAsync(matchId, false, ct)); }
    private static void Materialize(MatchTeam target, CompetitionRoster roster, OpenMatchTeamRequest q, string side) { var choices = q.Players?.ToArray() ?? []; var ids = choices.Select(x => x.CompetitionRosterPlayerId).ToArray(); if (ids.Length < 6) throw Invalid("match_requires_six_players", $"{side} requires at least six players."); if (ids.Distinct().Count() != ids.Length) throw Invalid("duplicate_match_player", $"{side} contains duplicate players."); var selected = new List<CompetitionRosterPlayer>(); foreach (var id in ids) { var p = roster.Players.SingleOrDefault(x => x.CompetitionRosterPlayerId == id); if (p is null) throw Invalid("match_player_wrong_roster", $"Player '{id}' does not belong to {side} roster."); if (p.Status != CompetitionRosterMemberStatus.Active) throw Conflict("match_player_not_active", $"Player '{id}' is not active."); selected.Add(p); } if (choices.Any(x => !x.JerseyNumber.HasValue)) throw Invalid("match_player_jersey_required", $"Every selected {side} player requires a jersey number."); if (choices.Any(x => x.JerseyNumber is < 1 or > 99)) throw Invalid("match_player_jersey_out_of_range", $"{side} jersey numbers must be between 1 and 99."); if (choices.Select(x => x.JerseyNumber!.Value).Distinct().Count() != choices.Length) throw Invalid("match_player_jersey_duplicate", $"{side} has duplicate jersey numbers."); var captainCount = choices.Count(x => x.IsMatchCaptain); if (captainCount == 0) throw Invalid("match_team_captain_required", $"{side} requires exactly one captain."); if (captainCount > 1) throw Invalid("match_team_multiple_captains", $"{side} cannot have more than one captain."); var byId = selected.ToDictionary(x => x.CompetitionRosterPlayerId); var map = choices.ToDictionary(x => x.CompetitionRosterPlayerId, x => target.AddPlayer(byId[x.CompetitionRosterPlayerId], x.JerseyNumber!.Value, x.IsMatchCaptain)); var liberoIds = q.LiberoCompetitionRosterPlayerIds?.ToArray() ?? []; if (liberoIds.Length > 2 || liberoIds.Distinct().Count() != liberoIds.Length) throw Invalid("too_many_match_liberos", "At most two distinct liberos are allowed."); for (var i = 0; i < liberoIds.Length; i++) { if (!map.TryGetValue(liberoIds[i], out var mp) || mp.CompetitionRosterPlayer.Role != PlayerRole.Libero) throw Invalid("invalid_match_libero", "Libero must be a selected player with Libero role."); target.AddLibero(mp, (byte)(i + 1)); } var staff = q.CompetitionRosterStaffIds?.ToArray() ?? []; if (staff.Distinct().Count() != staff.Length) throw Invalid("invalid_match_staff", "Staff cannot be duplicated."); foreach (var id in staff) { var s = roster.Staff.SingleOrDefault(x => x.CompetitionRosterStaffId == id); if (s is null || s.Status != CompetitionRosterMemberStatus.Active) throw Invalid("invalid_match_staff", "Staff must be active and belong to the same roster."); target.AddStaff(s); } }
    private static bool SameOpening(MatchSheet sheet, OpenMatchSheetRequest request) => SameTeam(sheet.Teams.Single(x => x.Side == MatchSide.Home), request.Home) && SameTeam(sheet.Teams.Single(x => x.Side == MatchSide.Away), request.Away) && sheet.TrackSubstitutions == request.TrackSubstitutions && sheet.TrackLiberoReplacements == request.TrackLiberoReplacements;
    private static bool SameTeam(MatchTeam team, OpenMatchTeamRequest request) { var expected = (request.Players ?? []).OrderBy(x => x.CompetitionRosterPlayerId).ToArray(); var actual = team.Players.OrderBy(x => x.CompetitionRosterPlayerId).ToArray(); return expected.Length == actual.Length && expected.Zip(actual).All(x => x.First.CompetitionRosterPlayerId == x.Second.CompetitionRosterPlayerId && x.First.JerseyNumber == x.Second.JerseyNumber && x.First.IsMatchCaptain == x.Second.IsMatchCaptain); }
    private static MatchOfficial RequiredOfficials(IReadOnlyList<MatchOfficial> os) { if (os.Count != 3 || Enum.GetValues<MatchOfficialRole>().Any(r => os.All(x => x.Role != r))) throw Conflict("match_officials_incomplete", "FirstReferee, SecondReferee and Scorer are required."); return os.Single(x => x.Role == MatchOfficialRole.Scorer); }
    private async Task<Domain.Fixtures.Match> RequiredMatch(int id, bool tracking, CancellationToken ct) => await matches.GetMatchAsync(id, tracking, ct) ?? throw new ResourceNotFoundException("Match", id);
    private async Task<CompetitionRoster> RequiredRoster(int? id, string side, bool tracking, CancellationToken ct) { if (!id.HasValue) throw Conflict("match_participants_not_resolved", "Match participants are not resolved."); return await rosters.GetAsync(id.Value, tracking, ct) ?? throw Conflict($"{side}_competition_roster_not_active", $"{side} CompetitionRoster does not exist."); }
    private static void EnsureRoster(CompetitionRoster r, string side) { if (r.Status != CompetitionRosterStatus.Active) throw Conflict($"{side}_competition_roster_not_active", $"{side} CompetitionRoster must be Active."); }
    private static OpenMatchTeamContextDto ToOpenTeam(CompetitionRoster r) => new(r.TeamEntryId, r.TeamEntry.TeamId, r.TeamEntry.Team.Name, r.CompetitionRosterId, r.Status, r.Players.Where(x => x.Status == CompetitionRosterMemberStatus.Active).Select(x => new OpenRosterPlayerDto(x.CompetitionRosterPlayerId, x.PlayerId, x.Player.PersonId, Name(x.Player.Person.FirstName, x.Player.Person.LastName), x.Role, HealthCardEvaluator.Evaluate(x.Player.Person).Status)).ToArray(), r.Staff.Where(x => x.Status == CompetitionRosterMemberStatus.Active).Select(x => new OpenRosterStaffDto(x.CompetitionRosterStaffId, x.CoachId, x.Coach.PersonId, Name(x.Coach.Person.FirstName, x.Coach.Person.LastName))).ToArray());
    private static MatchSheetSnapshotDto Snapshot(MatchSheet s, IReadOnlyList<MatchOfficial> os) { var teams = s.Teams.ToDictionary(x => x.Side, ToTeam); var session = s.Sessions.SingleOrDefault(x => x.Status == MatchSheetSessionStatus.Active) ?? s.Sessions.OrderByDescending(x => x.StartedAt).First(); var set = s.Sets.OrderByDescending(x => x.SetNumber).FirstOrDefault(); var current = set is null ? new MatchSheetCurrentStateDto(null, s.HomeSets, s.AwaySets, 0, 0, null, null, 0, 0, 0, 0) : new MatchSheetCurrentStateDto(set.SetNumber, s.HomeSets, s.AwaySets, set.HomePoints, set.AwayPoints, set.CurrentServingSide, Server(set, s), set.HomeRotationOffset, set.AwayRotationOffset, (byte)set.Timeouts.Count(x => x.MatchTeam.Side == MatchSide.Home), (byte)set.Timeouts.Count(x => x.MatchTeam.Side == MatchSide.Away)); return new(Summary(s), ToMatch(s.Match), ToCompetition(s.Match), teams[MatchSide.Home], teams[MatchSide.Away], os.Select(ToOfficial).OrderBy(x => x.Role).ToArray(), current, new(session.MatchSheetSessionId, session.SessionUuid, session.MatchOfficialId, session.DeviceId, session.Status, session.LastAcceptedSequence, session.StartedAt, session.EndedAt), new(s.SheetUuid, session.SessionUuid, session.LastAcceptedSequence), Operational(s)); }
    private static ScorerOperationalStateDto Operational(MatchSheet s) { var current = s.Sets.OrderByDescending(x => x.SetNumber).FirstOrDefault(); var home = s.Teams.Single(x => x.Side == MatchSide.Home).MatchTeamId; var away = s.Teams.Single(x => x.Side == MatchSide.Away).MatchTeamId; return new(Sql(s.Status), s.HomeSets, s.AwaySets, current?.SetNumber, s.Sets.OrderBy(x => x.SetNumber).Select(set => { var lineups = new Dictionary<string, int[]> { { "HOME", Lineup(set, home) }, { "AWAY", Lineup(set, away) } }; var events = s.Events.Where(x => x.MatchSetId == set.MatchSetId && x.Status == MatchEventStatus.Active).OrderBy(x => x.SequenceNumber).ToArray(); return new ScorerSetStateDto(set.SetNumber, Sql(set.Status), set.HomePoints, set.AwayPoints, Side(set.InitialServingSide), Side(set.CurrentServingSide), set.HomeRotationOffset, set.AwayRotationOffset, (byte)set.Timeouts.Count(x => x.MatchTeamId == home), (byte)set.Timeouts.Count(x => x.MatchTeamId == away), Side(set.WinnerSide), lineups, set.Substitutions.Select(x => new ScorerSubstitutionStateDto(Sql(x.MatchTeamId == home ? MatchSide.Home : MatchSide.Away), (int)x.LineupPosition - 1, x.PlayerOutMatchPlayerId, x.PlayerInMatchPlayerId)).ToArray(), set.LiberoReplacements.Select(x => new ScorerLiberoStateDto(Sql(x.MatchTeamId == home ? MatchSide.Home : MatchSide.Away), (int)x.LineupPosition - 1, x.LiberoMatchPlayerId, x.ReplacedMatchPlayerId, !x.ExitedAt.HasValue)).ToArray(), events.Where(x => x.EventType == MatchEventType.Point).Select(x => Sql(x.Side!.Value)).ToArray(), events.LastOrDefault(x => x.EventType is MatchEventType.Point or MatchEventType.PointCorrection or MatchEventType.Substitution or MatchEventType.LiberoEnter or MatchEventType.LiberoExit or MatchEventType.Timeout) is { } last ? Event(last.EventType) : null, LiberoPlans(set, home, away)); }).ToArray(), s.HomeSets == 3 || s.AwaySets == 3, s.Status == MatchSheetStatus.Closed, s.Status == MatchSheetStatus.Closed); }
    private static int[] Lineup(MatchSet set, int matchTeamId) => set.Lineups.SingleOrDefault(x => x.MatchTeamId == matchTeamId)?.Positions.OrderBy(x => x.Position).Select(x => x.MatchPlayerId).ToArray() ?? [];
    private static IReadOnlyDictionary<string, ScorerLiberoPlanDto> LiberoPlans(MatchSet set, int home, int away) => new Dictionary<string, ScorerLiberoPlanDto> { ["HOME"] = LiberoPlan(set, home), ["AWAY"] = LiberoPlan(set, away) };
    private static ScorerLiberoPlanDto LiberoPlan(MatchSet set, int teamId) { var plan = set.LiberoPlans.SingleOrDefault(x => x.MatchTeamId == teamId); return plan is null ? new(false, null, []) : new(true, plan.LiberoMatchPlayerId, plan.LogicalPositions.Select(x => (int)x - 1).ToArray()); }
    private static string? Side(MatchSide? side) => side.HasValue ? Sql(side.Value) : null; private static string Sql<T>(T value) => string.Concat(value!.ToString()!.Select((c, i) => i > 0 && char.IsUpper(c) ? "_" + c : c.ToString())).ToUpperInvariant(); private static string Event(MatchEventType value) => value switch { MatchEventType.PointCorrection => "CORRECT_LAST_POINT", MatchEventType.MatchClosed => "MATCH_CLOSE", _ => Sql(value) };
    private static int? Server(MatchSet set, MatchSheet sheet) { if (set.CurrentServingSide is null) return null; var team = sheet.Teams.Single(x => x.Side == set.CurrentServingSide); var lineup = set.Lineups.SingleOrDefault(x => x.MatchTeamId == team.MatchTeamId); if (lineup is null) return null; var court = MatchCourtStateCalculator.Calculate(lineup, team.Side == MatchSide.Home ? set.HomeRotationOffset : set.AwayRotationOffset, set.Substitutions.Where(x => x.MatchTeamId == team.MatchTeamId), []); return MatchCourtStateCalculator.Server(court); }
    private static MatchSheetTeamDto ToTeam(MatchTeam x) => new(x.MatchTeamId, x.MatchTeamUuid, x.Side, x.TeamEntryId, x.TeamEntry.TeamId, x.TeamEntry.Team.Name, x.CompetitionRosterId, x.Players.Select(p => new MatchSheetPlayerDto(p.MatchPlayerId, p.MatchPlayerUuid, p.CompetitionRosterPlayerId, p.CompetitionRosterPlayer.PlayerId, p.CompetitionRosterPlayer.Player.PersonId, Name(p.CompetitionRosterPlayer.Player.Person.FirstName, p.CompetitionRosterPlayer.Player.Person.LastName), p.JerseyNumber, p.CompetitionRosterPlayer.Role, p.IsMatchCaptain, p.Status, HealthCardEvaluator.Evaluate(p.CompetitionRosterPlayer.Player.Person).Status)).ToArray(), x.Staff.Select(s => new MatchSheetStaffDto(s.MatchTeamStaffId, s.MatchTeamStaffUuid, s.CompetitionRosterStaffId, s.CompetitionRosterStaff.CoachId, s.CompetitionRosterStaff.Coach.PersonId, Name(s.CompetitionRosterStaff.Coach.Person.FirstName, s.CompetitionRosterStaff.Coach.Person.LastName), s.Status)).ToArray(), x.Liberos.OrderBy(l => l.LiberoOrder).Select(l => new MatchSheetLiberoDto(l.MatchLiberoId, l.MatchLiberoUuid, l.MatchPlayerId, l.LiberoOrder)).ToArray());
    private static MatchSheetOfficialDto ToOfficial(MatchOfficial x) => new(x.MatchOfficialId, x.Role, x.RefereeId, x.Referee.PersonId, Name(x.Referee.Person.FirstName, x.Referee.Person.LastName), HealthCardEvaluator.Evaluate(x.Referee.Person).Status);
    private static MatchContextDto ToMatch(Domain.Fixtures.Match x) => new(x.MatchId, x.Status, x.MatchDate, x.RoundNumber, x.MatchNumber, x.HomeTeamEntryId!.Value, x.AwayTeamEntryId!.Value, x.Venue?.Name); private static CompetitionContextDto ToCompetition(Domain.Fixtures.Match x) => new(x.CompetitionId, x.Competition.Name, x.Competition.Season.Name, x.Competition.Division.Name, x.Phase.Name, x.PhaseGroup?.Name, x.Series?.Name); private static MatchSheetSummaryDto Summary(MatchSheet x) => new(x.MatchSheetId, x.SheetUuid, x.Status, x.OpenedAt); private static string Name(string f, string l) => $"{f} {l}";
    private static RequestValidationException Invalid(string c, string m) => new(c, m); private static ResourceConflictException Conflict(string c, string m) => new(c, m);
    private static ResourceConflictException OpeningConflict(MatchReadinessIssueDto issue) => issue.Code switch
    {
        "match_readiness_match_not_scheduled" => Conflict("match_not_scheduled", issue.Message),
        "match_readiness_roster_missing" or "match_readiness_roster_not_active" => Conflict(issue.Side == MatchSide.Home ? "home_competition_roster_not_active" : "away_competition_roster_not_active", issue.Message),
        "match_readiness_insufficient_active_players" => Conflict("match_roster_insufficient_active_players", issue.Message),
        _ => Conflict("match_officials_incomplete", issue.Message)
    };
}
