using LigaVolley.Domain.CompetitionFormats;
using LigaVolley.Domain.Competitions;
using LigaVolley.Domain.Divisions;
using LigaVolley.Domain.Fixtures;
using LigaVolley.Domain.MatchSheets;

namespace LigaVolley.Application.PublicQueries;

public sealed record PublicSeasonDto(int SeasonId, short Year, string Name);
public sealed record PublicDivisionDto(int DivisionId,string Name,short LevelOrder,Gender Gender);
public sealed record PublicCompetitionSummaryDto(int CompetitionId,string Name,PublicSeasonDto Season,PublicDivisionDto Division,CompetitionPeriodType PeriodType,DateOnly? StartDate,DateOnly? EndDate,CompetitionStatus Status);
public sealed record PublicCompetitionTeamDto(int TeamEntryId,int TeamId,string TeamName);
public sealed record PublicTeamSummaryDto(int TeamEntryId,string TeamName,string? ClubLogoUrl);
public sealed record PublicVenueDto(int VenueId,string Name);
public sealed record PublicSetResultDto(short SetNumber,int HomePoints,int AwayPoints);
public sealed record PublicMatchScoreDto(int HomeSets,int AwaySets,IReadOnlyList<PublicSetResultDto> Sets);
public sealed record PublicCompetitionGroupDto(int PhaseGroupId,string Code,string Name,GroupRole GroupRole,short Sequence);
public sealed record PublicPlayoffParticipantSourceDto(SeriesParticipantSourceType SourceType,string? SourceSeriesCode,string DisplayName);
public sealed record PublicPlayoffParticipantDto(byte Side,PublicTeamSummaryDto? Team,PublicPlayoffParticipantSourceDto? Source);
public sealed record PublicPlayoffMatchDto(int MatchId,short MatchNumber,PublicTeamSummaryDto HomeTeam,PublicTeamSummaryDto AwayTeam,MatchStatus Status,DateTimeOffset? MatchDate,PublicVenueDto? Venue,PublicMatchScoreDto? Score);
public sealed record PublicPlayoffSeriesDto(int SeriesId,string Code,string Name,short Sequence,PlayoffSeriesStatus Status,PublicPlayoffParticipantDto Team1,PublicPlayoffParticipantDto Team2,short Team1InitialWins,short Team2InitialWins,int Team1RealWins,int Team2RealWins,int Team1SeriesWins,int Team2SeriesWins,short WinsRequired,int? WinnerTeamEntryId,IReadOnlyList<PublicPlayoffMatchDto> Matches);
public sealed record PublicCompetitionPhaseDto(int PhaseId,string Code,string Name,PhaseType PhaseType,PhaseRole PhaseRole,short Sequence,CompetitionPhaseStatus Status,IReadOnlyList<PublicCompetitionGroupDto> Groups,IReadOnlyList<PublicPlayoffSeriesDto> PlayoffSeries);
public sealed record PublicCompetitionDto(int CompetitionId,string Name,PublicSeasonDto Season,PublicDivisionDto Division,CompetitionPeriodType PeriodType,DateOnly? StartDate,DateOnly? EndDate,CompetitionStatus Status,IReadOnlyList<PublicCompetitionTeamDto> Teams,IReadOnlyList<PublicCompetitionPhaseDto> Phases);
public sealed record PublicFixtureMatchDto(int MatchId,short? MatchNumber,PublicTeamSummaryDto HomeTeam,PublicTeamSummaryDto AwayTeam,DateTimeOffset? MatchDate,PublicVenueDto? Venue,MatchStatus Status,PublicMatchScoreDto? Score);
public sealed record PublicFixtureRoundDto(short RoundNumber,IReadOnlyList<PublicFixtureMatchDto> Matches);
public sealed record PublicFixtureGroupDto(int PhaseGroupId,string Code,string Name,GroupRole GroupRole,short Sequence,IReadOnlyList<PublicFixtureRoundDto> Rounds);
public sealed record PublicFixtureSeriesDto(int SeriesId,string Code,string Name,short Sequence,PlayoffSeriesStatus Status,PublicTeamSummaryDto? Team1,PublicTeamSummaryDto? Team2,short Team1InitialWins,short Team2InitialWins,short WinsRequired,int Team1Wins,int Team2Wins,int? WinnerTeamEntryId,IReadOnlyList<PublicFixtureMatchDto> Matches);
public sealed record PublicFixturePhaseDto(int PhaseId,string Code,string Name,PhaseType PhaseType,PhaseRole PhaseRole,short Sequence,IReadOnlyList<PublicFixtureRoundDto> Rounds,IReadOnlyList<PublicFixtureGroupDto> Groups,IReadOnlyList<PublicFixtureSeriesDto> Series);
public sealed record PublicCompetitionFixtureDto(int CompetitionId,string CompetitionName,IReadOnlyList<PublicFixturePhaseDto> Phases);
public sealed record PublicStandingRowDto(int Position,int TeamEntryId,string TeamName,int Played,int Won,int Lost,int SetsWon,int SetsLost,decimal? SetRatio,int PointsWon,int PointsLost,decimal? PointRatio,int TablePoints,bool IsTied);
public sealed record PublicStandingsTableDto(int PhaseId,string PhaseCode,string PhaseName,short PhaseSequence,int? PhaseGroupId,string? PhaseGroupCode,string? PhaseGroupName,short? PhaseGroupSequence,bool IsFinal,IReadOnlyList<PublicStandingRowDto> Rows);
public sealed record PublicCompetitionStandingsDto(int CompetitionId,string CompetitionName,IReadOnlyList<PublicStandingsTableDto> Tables);
public sealed record PublicMatchCompetitionDto(int CompetitionId,string CompetitionName,int SeasonId,short SeasonYear,int DivisionId,string DivisionName,Gender Gender);
public sealed record PublicMatchScopeDto(int PhaseId,string PhaseCode,string PhaseName,int? PhaseGroupId,string? PhaseGroupCode,string? PhaseGroupName,int? SeriesId,string? SeriesCode,string? SeriesName);
public sealed record PublicMatchResultDto(int HomeSets,int AwaySets,int WinnerTeamEntryId,IReadOnlyList<PublicSetResultDto> Sets);
public sealed record PublicMatchDto(int MatchId,PublicMatchCompetitionDto Competition,PublicMatchScopeDto Scope,PublicTeamSummaryDto HomeTeam,PublicTeamSummaryDto AwayTeam,DateTimeOffset? MatchDate,PublicVenueDto? Venue,MatchStatus Status,short? RoundNumber,short? MatchNumber,PublicMatchResultDto? Result,bool LiveAvailable);
public sealed record PublicLiveTeamDto(int TeamEntryId,string TeamName,int SetsWon,string? ClubLogoUrl);
public sealed record PublicLiveSetDto(short SetNumber,MatchSetStatus Status,int HomePoints,int AwayPoints,MatchSide? WinnerSide);
public sealed record PublicCourtPlayerDto(string JerseyNumber,string DisplayName,bool IsLibero);
public sealed record PublicCourtPositionDto(byte Position,PublicCourtPlayerDto Player);
public sealed record PublicCourtDto(IReadOnlyList<PublicCourtPositionDto> Positions);
public sealed record PublicServingPlayerDto(short JerseyNumber,string DisplayName);
public sealed record PublicLiveMatchDto(int MatchId,MatchStatus Status,PublicLiveTeamDto Home,PublicLiveTeamDto Away,short? CurrentSetNumber,IReadOnlyList<PublicLiveSetDto> Sets,MatchSide? ServingSide,PublicCourtDto? HomeCourt,PublicCourtDto? AwayCourt,DateTimeOffset? LastUpdatedAt,DateTimeOffset ServerTime,PublicServingPlayerDto? ServingPlayer);
