using LigaVolley.Application.Abstractions.Persistence;
using LigaVolley.Application.Common;
using LigaVolley.Application.People;
using LigaVolley.Domain.CompetitionRosters;
using LigaVolley.Domain.Competitions;
using LigaVolley.Domain.TeamEntries;
namespace LigaVolley.Application.CompetitionRosters;
public sealed class CompetitionRosterService(ICompetitionRosterRepository rosters,ITeamEntryRepository entries,ICompetitionRepository competitions,IPeopleRepository people,IUnitOfWork unit)
{
 public async Task<CompetitionRosterDto> GetAsync(int competitionId,int teamEntryId,CancellationToken ct)=>Map(await RequiredRoster(competitionId,teamEntryId,false,ct));
 public async Task<CompetitionRosterDto> CreateAsync(int competitionId,int teamEntryId,CancellationToken ct)
 {
  await using var tx=await unit.BeginSerializableTransactionAsync(ct); await rosters.AcquireTeamEntryLockAsync(teamEntryId,ct); var entry=await RequiredEditableEntry(competitionId,teamEntryId,ct);
  if(await rosters.GetAsync(teamEntryId,false,ct) is not null)throw Conflict("competition_roster_already_exists","A roster already exists for this TeamEntry.");
  var roster=new CompetitionRoster(entry);rosters.Add(roster);await unit.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(roster);
 }
 public async Task<CompetitionRosterDto> ChangeStatusAsync(int c,int e,ChangeCompetitionRosterStatusRequest request,CancellationToken ct)=>await Mutate(c,e,ct,r=>{if(request.Status==CompetitionRosterStatus.Active)r.Activate();else if(request.Status==CompetitionRosterStatus.Closed)r.Close();else throw Conflict("competition_roster_invalid_transition","Requested roster transition is not allowed.");});
 public async Task<CompetitionRosterDto> AddPlayerAsync(int c,int e,AddCompetitionRosterPlayerRequest request,CancellationToken ct)=>await Mutate(c,e,ct,async r=>{var p=await people.GetPlayerAsync(request.PlayerId,true,ct)??throw new ResourceNotFoundException("Player",request.PlayerId);try{r.AddPlayer(p,request.Role);}catch(Exception x){throw Translate(x);}});
 public async Task<CompetitionRosterDto> UpdatePlayerAsync(int c,int e,int id,UpdateCompetitionRosterPlayerRequest request,CancellationToken ct)=>await Mutate(c,e,ct,r=>{var m=r.Players.SingleOrDefault(x=>x.CompetitionRosterPlayerId==id)??throw new ResourceNotFoundException("CompetitionRosterPlayer",id);try{r.UpdatePlayer(m,request.Role);}catch(Exception x){throw Translate(x);}});
 public async Task<CompetitionRosterDto> ChangePlayerStatusAsync(int c,int e,int id,ChangeRosterMemberStatusRequest request,CancellationToken ct)=>await Mutate(c,e,ct,r=>{var m=r.Players.SingleOrDefault(x=>x.CompetitionRosterPlayerId==id)??throw new ResourceNotFoundException("CompetitionRosterPlayer",id);try{r.ChangePlayerStatus(m,request.Status);}catch(Exception x){throw Translate(x);}});
 public async Task<CompetitionRosterDto> AddStaffAsync(int c,int e,AddCompetitionRosterStaffRequest request,CancellationToken ct)=>await Mutate(c,e,ct,async r=>{var p=await people.GetCoachAsync(request.CoachId,true,ct)??throw new ResourceNotFoundException("Coach",request.CoachId);try{r.AddStaff(p);}catch(Exception x){throw Translate(x);}});
 public async Task<CompetitionRosterDto> ChangeStaffStatusAsync(int c,int e,int id,ChangeRosterMemberStatusRequest request,CancellationToken ct)=>await Mutate(c,e,ct,r=>{var m=r.Staff.SingleOrDefault(x=>x.CompetitionRosterStaffId==id)??throw new ResourceNotFoundException("CompetitionRosterStaff",id);try{r.ChangeStaffStatus(m,request.Status);}catch(Exception x){throw Translate(x);}});
 private async Task<CompetitionRosterDto> Mutate(int c,int e,CancellationToken ct,Action<CompetitionRoster> action){await using var tx=await unit.BeginSerializableTransactionAsync(ct);await rosters.AcquireTeamEntryLockAsync(e,ct);await RequiredEditableEntry(c,e,ct);var r=await RequiredRoster(c,e,true,ct);try{action(r);}catch(Domain.Common.DomainValidationException x){throw Translate(x);}await unit.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(r);}
 private async Task<CompetitionRosterDto> Mutate(int c,int e,CancellationToken ct,Func<CompetitionRoster,Task> action){await using var tx=await unit.BeginSerializableTransactionAsync(ct);await rosters.AcquireTeamEntryLockAsync(e,ct);await RequiredEditableEntry(c,e,ct);var r=await RequiredRoster(c,e,true,ct);await action(r);await unit.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(r);}
 private async Task<TeamEntry> RequiredEditableEntry(int c,int e,CancellationToken ct){var competition=await competitions.GetAsync(c,true,ct)??throw new ResourceNotFoundException("Competition",c);var entry=await entries.GetAsync(c,e,true,ct)??throw Conflict("competition_roster_team_entry_mismatch","TeamEntry does not belong to Competition.");if(!entry.IsValid)throw Conflict("competition_roster_team_entry_not_editable","TeamEntry is not operational.");if(competition.Status is CompetitionStatus.Finished or CompetitionStatus.Cancelled)throw Conflict("competition_roster_competition_not_editable","Competition is not editable.");return entry;}
 private async Task<CompetitionRoster> RequiredRoster(int c,int e,bool tracking,CancellationToken ct){var entry=await entries.GetAsync(c,e,false,ct);if(entry is null)throw Conflict("competition_roster_team_entry_mismatch","TeamEntry does not belong to Competition.");return await rosters.GetAsync(e,tracking,ct)??throw new ResourceNotFoundException("CompetitionRoster",e);}
 private static Exception Translate(Exception x){var m=x.Message;if(m.Contains("Closed"))return Conflict("competition_roster_closed",m);if(m.Contains("15"))return Conflict("competition_roster_player_limit_exceeded",m);if(m.Contains("libero"))return Conflict("competition_roster_libero_limit_exceeded",m);if(m.Contains("Player already"))return Conflict("competition_roster_player_already_exists",m);if(m.Contains("Coach already"))return Conflict("competition_roster_staff_already_exists",m);if(m.Contains("coaches"))return Conflict("competition_roster_staff_limit_exceeded",m);if(m.Contains("activated")||m.Contains("closed administratively"))return Conflict("competition_roster_invalid_transition",m);return x;}
 private static ResourceConflictException Conflict(string code,string message)=>new(code,message);
 private static CompetitionRosterDto Map(CompetitionRoster r){var ps=r.Players.OrderByDescending(x=>x.Status==CompetitionRosterMemberStatus.Active).ThenBy(x=>x.Player.Person.LastName).ThenBy(x=>x.Player.Person.FirstName).Select(x=>new CompetitionRosterPlayerDto(x.CompetitionRosterPlayerId,x.PlayerId,x.Player.PersonId,x.Player.Person.FirstName,x.Player.Person.LastName,x.Role,x.Status,HealthCardEvaluator.Evaluate(x.Player.Person).Status)).ToArray();var ss=r.Staff.OrderByDescending(x=>x.Status==CompetitionRosterMemberStatus.Active).ThenBy(x=>x.Coach.Person.LastName).ThenBy(x=>x.Coach.Person.FirstName).Select(x=>new CompetitionRosterStaffDto(x.CompetitionRosterStaffId,x.CoachId,x.Coach.PersonId,x.Coach.Person.FirstName,x.Coach.Person.LastName,x.Status)).ToArray();return new(r.CompetitionRosterId,r.TeamEntry.CompetitionId,r.TeamEntryId,r.TeamEntry.TeamId,r.TeamEntry.Team.Name,r.Status,ps.Count(x=>x.Status==CompetitionRosterMemberStatus.Active),ss.Count(x=>x.Status==CompetitionRosterMemberStatus.Active),ps.Count(x=>x.Status==CompetitionRosterMemberStatus.Active&&x.Role==PlayerRole.Libero),ps,ss);}
}
