<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LigaVolley.Application\LigaVolley.Application.csproj" />
    <ProjectReference Include="..\LigaVolley.Infrastructure\LigaVolley.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a8224f8c-3be1-4bca-82dc-2e1fafbdeb77</UserSecretsId>
  </PropertyGroup>

</Project>
