using System.Reflection;
using LigaVolley.Application.Abstractions.Persistence;
using LigaVolley.Application.Common;
using LigaVolley.Application.Fixtures;
using LigaVolley.Domain.Competitions;
using LigaVolley.Domain.CompetitionFormats;
using LigaVolley.Domain.Divisions;
using LigaVolley.Domain.Seasons;
using LigaVolley.Domain.TeamEntries;
using LigaVolley.Domain.Teams;
namespace LigaVolley.Application.Tests;
public sealed class FixtureServiceTests
{
    [Fact] public async Task Generate_EightTeams_CreatesOnlyInitialMirroredPhaseAndSchedulesCompetition()
    { var f=Fixture(8,8,FixtureMode.MirroredHomeAway,2,8);var result=await f.Service.GenerateInitialAsync(1,new(12345),default);Assert.Equal(56,result.MatchesCreated);Assert.Equal(CompetitionStatus.Scheduled,f.Competition.Status);Assert.Equal(56,f.Fixtures.Matches.Count);Assert.All(f.Fixtures.Matches,x=>{Assert.Null(x.MatchDate);Assert.Null(x.VenueId);Assert.Null(x.SeriesId);}); }
    [Fact] public async Task Generate_TenTeams_CreatesOnlyRegularAndNoLaterScopeMatches()
    { var f=Fixture(10,10,FixtureMode.BalancedRandom,1,10,addLaterPhases:true);var result=await f.Service.GenerateInitialAsync(1,new(7),default);Assert.Equal(45,result.MatchesCreated);Assert.All(f.Fixtures.Matches,x=>Assert.Equal(f.Competition.Phases[0],x.Phase));Assert.Empty(f.Fixtures.Matches.Where(x=>x.Phase!=f.Competition.Phases[0])); }
    [Fact] public async Task Generate_RejectsMissingCompetition() { var service=new FixtureService(new FakeCompetitionRepository(),new FakeTeamEntryRepository(),new FakeFixtureRepository(),new FakeUnitOfWork());await Assert.ThrowsAsync<ResourceNotFoundException>(()=>service.GenerateInitialAsync(99,new(1),default)); }
    [Fact] public async Task Generate_RejectsCompetitionOutsideDraft() { var f=Fixture(2,4,FixtureMode.BalancedRandom,1,2);f.Competition.ChangeStatus(CompetitionStatus.Cancelled);var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("fixture_competition_not_draft",ex.Code); }
    [Fact] public async Task Generate_RejectsTooFewValidTeams() { var f=Fixture(4,8,FixtureMode.BalancedRandom,1,3);var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("fixture_team_count_out_of_range",ex.Code); }
    [Fact] public async Task Generate_RejectsIncoherentCountAboveMaximum() { var f=Fixture(2,4,FixtureMode.BalancedRandom,1,5);var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("fixture_team_count_out_of_range",ex.Code); }
    [Fact] public async Task Generate_RejectsExistingFixture() { var f=Fixture(2,4,FixtureMode.BalancedRandom,1,2);f.Fixtures.GenerationExists=true;var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("initial_fixture_already_generated",ex.Code); }
    [Fact] public async Task Generate_RejectsZeroInitialScopes() { var f=Fixture(2,4,FixtureMode.Playoff,null,2);var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("unsupported_initial_fixture_scope",ex.Code); }
    [Fact] public async Task Generate_RejectsMultipleInitialScopes() { var f=Fixture(2,4,FixtureMode.BalancedRandom,1,2);var extra=new FormatPhase("OTHER","Other",PhaseType.RoundRobin,PhaseRole.Regular,1,1,FixtureMode.BalancedRandom);f.Format.Phases.Add(extra);var rebuilt=Competition(f.Format);SetId(rebuilt,1);SetId(rebuilt.Phases[0],10);SetId(rebuilt.Phases[1],11);f.Competitions.Seed(1,rebuilt);var ex=await Assert.ThrowsAsync<ResourceConflictException>(()=>f.Service.GenerateInitialAsync(1,new(1),default));Assert.Equal("unsupported_initial_fixture_scope",ex.Code); }
    [Fact] public async Task Generate_PersistenceFailureDoesNotCommitAnyState() { var f=Fixture(2,4,FixtureMode.BalancedRandom,1,2,unit:new FailingUnitOfWork());await Assert.ThrowsAsync<InvalidOperationException>(()=>f.Service.GenerateInitialAsync(1,new(1),default)); /* staged objects are discarded with the failed request scope; SaveChanges commits nothing */ }

    private static TestFixture Fixture(short min,short max,FixtureMode mode,short? rounds,int valid,bool addLaterPhases=false,IUnitOfWork? unit=null)
    { var format=new CompetitionFormat("F","Format",null,min,max);format.Phases.Add(new("REG","Regular",mode==FixtureMode.Playoff?PhaseType.Playoff:PhaseType.RoundRobin,PhaseRole.Regular,1,rounds,mode));if(mode==FixtureMode.Playoff)format.Phases[0].Series.Add(new("P","P",1,1,0,0));if(addLaterPhases){var second=new FormatPhase("SECOND","Second",PhaseType.GroupStage,PhaseRole.Championship,2,null,null);second.Groups.Add(new("CHAMP","Champ",GroupRole.Championship,1,1,FixtureMode.BalancedRandom,CarryOverMode.None));second.Groups.Add(new("RELEG","Releg",GroupRole.Relegation,2,1,FixtureMode.BalancedRandom,CarryOverMode.None));format.Phases.Add(second);var playoff=new FormatPhase("SF","SF",PhaseType.Playoff,PhaseRole.Semifinal,3,null,FixtureMode.Playoff);playoff.Series.Add(new("SF1","SF1",1,1,0,0));format.Phases.Add(playoff);}var competition=Competition(format);SetId(competition,1);for(var i=0;i<competition.Phases.Count;i++){SetId(competition.Phases[i],10+i);foreach(var g in competition.Phases[i].Groups)SetId(g,100+i);}var compRepo=new FakeCompetitionRepository();compRepo.Seed(1,competition);var entryRepo=new FakeTeamEntryRepository();for(var i=1;i<=valid;i++){var team=new Team($"T{i}",Gender.Female,null);SetId(team,i);var entry=new TeamEntry(competition,team,null);SetId(entry,i);entryRepo.Seed(1,i,entry);}var fixtureRepo=new FakeFixtureRepository();var service=new FixtureService(compRepo,entryRepo,fixtureRepo,unit??new FakeUnitOfWork());return new(service,fixtureRepo,competition,format,compRepo); }
    private static Competition Competition(CompetitionFormat format)=>new("Competition",new Season(2026,"2026",null,null),new Division("A",1,Gender.Female),format,CompetitionPeriodType.Annual,null,null);
    private static void SetId(object value,int id)=>value.GetType().GetProperties().Single(x=>x.Name.EndsWith("Id")&&x.Name==value.GetType().Name+"Id"||x.Name switch{"CompetitionPhaseId" when value is CompetitionPhase=>true,"PhaseGroupId" when value is CompetitionPhaseGroup=>true,"TeamEntryId" when value is TeamEntry=>true,"TeamId" when value is Team=>true,_=>false}).SetValue(value,id);
    private sealed record TestFixture(FixtureService Service,FakeFixtureRepository Fixtures,Competition Competition,CompetitionFormat Format,FakeCompetitionRepository Competitions);
}
