using LigaVolley.Application.MatchSheets;
namespace LigaVolley.Api.Endpoints.Scorer;
internal static class ScorerMatchSheetEndpoints
{
 public static IEndpointRouteBuilder MapScorerMatchSheetEndpoints(this IEndpointRouteBuilder e){var g=e.MapGroup("/api/scorer/matches/{matchId:int}").WithTags("Scorer Match Sheet");
 // Example: GET /api/scorer/matches/1/open-context
 g.MapGet("/open-context",async(int matchId,MatchSheetService s,CancellationToken ct)=>Results.Ok(await s.GetOpenContextAsync(matchId,ct))).Produces<OpenMatchContextDto>().ProducesProblem(404).ProducesProblem(409);
 // Example: POST /api/scorer/matches/1/open
 // Body: { "clientRequestId": "91489d08-52cb-4c04-8af5-ca76400931f3", "deviceId": "scorer-tablet-07", "home": { "players": [{"competitionRosterPlayerId":101,"jerseyNumber":4,"isMatchCaptain":true},{"competitionRosterPlayerId":102,"jerseyNumber":8,"isMatchCaptain":false},{"competitionRosterPlayerId":103,"jerseyNumber":12,"isMatchCaptain":false},{"competitionRosterPlayerId":104,"jerseyNumber":14,"isMatchCaptain":false},{"competitionRosterPlayerId":105,"jerseyNumber":18,"isMatchCaptain":false},{"competitionRosterPlayerId":106,"jerseyNumber":21,"isMatchCaptain":false}], "liberoCompetitionRosterPlayerIds": [], "competitionRosterStaffIds": [] }, "away": { "players": [{"competitionRosterPlayerId":201,"jerseyNumber":3,"isMatchCaptain":true},{"competitionRosterPlayerId":202,"jerseyNumber":5,"isMatchCaptain":false},{"competitionRosterPlayerId":203,"jerseyNumber":7,"isMatchCaptain":false},{"competitionRosterPlayerId":204,"jerseyNumber":9,"isMatchCaptain":false},{"competitionRosterPlayerId":205,"jerseyNumber":11,"isMatchCaptain":false},{"competitionRosterPlayerId":206,"jerseyNumber":15,"isMatchCaptain":false}], "liberoCompetitionRosterPlayerIds": [], "competitionRosterStaffIds": [] } }
 g.MapPost("/open",async(int matchId,OpenMatchSheetRequest r,MatchSheetService s,CancellationToken ct)=>{var x=await s.OpenAsync(matchId,r,ct);return x.AlreadyOpen?Results.Ok(x):Results.Created($"/api/scorer/matches/{matchId}/sheet",x);}).Produces<OpenMatchSheetResponse>(201).Produces<OpenMatchSheetResponse>(200).ProducesProblem(400).ProducesProblem(404).ProducesProblem(409);
 // Example: GET /api/scorer/matches/1/sheet
 g.MapGet("/sheet",async(int matchId,MatchSheetService s,CancellationToken ct)=>Results.Ok(await s.GetSheetAsync(matchId,ct))).WithSummary("Get the canonical MatchSheet reconciliation snapshot").WithDescription("Returns the persisted sporting state plus current or last session, device and LastAcceptedSequence. It never creates a session.").Produces<MatchSheetSnapshotDto>().ProducesProblem(404);return e;}
}
