using System.Net;using System.Net.Http.Json;using System.Text.Json;using System.Text.Json.Serialization;using LigaVolley.Application.MatchOfficials;using LigaVolley.Domain.MatchOfficials;using LigaVolley.Domain.People;using LigaVolley.Domain.Fixtures;using LigaVolley.Domain.CompetitionFormats;using LigaVolley.Domain.Competitions;using LigaVolley.Domain.Seasons;using LigaVolley.Domain.Divisions;using LigaVolley.Domain.Teams;using LigaVolley.Domain.TeamEntries;using LigaVolley.Infrastructure.Persistence;using Microsoft.Extensions.DependencyInjection;using Microsoft.EntityFrameworkCore;
namespace LigaVolley.IntegrationTests;
public sealed class MatchOfficialEndpointsTests(LigaVolleyApiFactory factory):IClassFixture<LigaVolleyApiFactory>
{
 private static readonly JsonSerializerOptions Json=new(JsonSerializerDefaults.Web){Converters={new JsonStringEnumConverter()}};
 [Fact]public async Task Full_assignment_uniqueness_health_warning_and_scorer_replacement_flow(){var data=await Seed();var empty=await factory.Client.GetFromJsonAsync<MatchOfficialDto[]>($"/api/admin/matches/{data.MatchId}/officials",Json);Assert.Empty(empty!);var first=await factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[0],MatchOfficialRole.FirstReferee),Json);Assert.Equal(HttpStatusCode.Created,first.StatusCode);Assert.Equal(HealthCardStatus.Missing,(await first.Content.ReadFromJsonAsync<MatchOfficialDto>(Json))!.HealthCardStatus);var sameRole=await factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[1],MatchOfficialRole.FirstReferee),Json);Assert.Equal(HttpStatusCode.Conflict,sameRole.StatusCode);var sameRef=await factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[0],MatchOfficialRole.SecondReferee),Json);Assert.Equal(HttpStatusCode.Conflict,sameRef.StatusCode);await factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[1],MatchOfficialRole.SecondReferee),Json);await factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[2],MatchOfficialRole.Scorer),Json);await SetStatus(data.MatchId,MatchStatus.InProgress);Assert.Equal(HttpStatusCode.Conflict,(await factory.Client.DeleteAsync($"/api/admin/matches/{data.MatchId}/officials/{(await first.Content.ReadFromJsonAsync<MatchOfficialDto>(Json))!.MatchOfficialId}")).StatusCode);var replace=await factory.Client.PutAsJsonAsync($"/api/scorer/matches/{data.MatchId}/officials/FirstReferee",new ReplaceMatchOfficialRequest(data.Referees[3]),Json);Assert.Equal(HttpStatusCode.OK,replace.StatusCode);Assert.Equal(data.Referees[3],(await replace.Content.ReadFromJsonAsync<MatchOfficialDto>(Json))!.RefereeId);}
 [Fact]public async Task Concurrent_same_role_creates_one_assignment(){var data=await Seed();var responses=await Task.WhenAll(factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[0],MatchOfficialRole.FirstReferee),Json),factory.Client.PostAsJsonAsync($"/api/admin/matches/{data.MatchId}/officials",new AddMatchOfficialRequest(data.Referees[1],MatchOfficialRole.FirstReferee),Json));Assert.Single(responses.Where(x=>x.StatusCode==HttpStatusCode.Created));Assert.Single(responses.Where(x=>x.StatusCode==HttpStatusCode.Conflict));}
 [Fact]public async Task Missing_match_returns_problem_details(){var response=await factory.Client.GetAsync("/api/admin/matches/2147483647/officials");Assert.Equal(HttpStatusCode.NotFound,response.StatusCode);Assert.Equal("application/problem+json",response.Content.Headers.ContentType?.MediaType);var json=await response.Content.ReadFromJsonAsync<JsonElement>();Assert.Equal("not_found",json.GetProperty("code").GetString());}
 [Fact]public async Task OpenApi_documents_admin_and_scorer_contracts(){var json=await factory.Client.GetStringAsync("/swagger/v1/swagger.json");using var doc=JsonDocument.Parse(json);var paths=doc.RootElement.GetProperty("paths");var collection=paths.GetProperty("/api/admin/matches/{matchId}/officials");Assert.True(collection.TryGetProperty("get",out _));Assert.True(collection.TryGetProperty("post",out var post));Assert.True(post.GetProperty("responses").TryGetProperty("201",out _));Assert.True(post.GetProperty("responses").TryGetProperty("409",out _));var item=paths.GetProperty("/api/admin/matches/{matchId}/officials/{matchOfficialId}");Assert.True(item.TryGetProperty("put",out _));Assert.True(item.TryGetProperty("delete",out _));Assert.True(paths.GetProperty("/api/scorer/matches/{matchId}/officials/{role}").TryGetProperty("put",out _));}
 private async Task<(int MatchId,int[] Referees)> Seed(){await using var scope=factory.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<LigaVolleyDbContext>();var suffix=Guid.NewGuid().ToString("N")[..8];var format=new CompetitionFormat($"MO{suffix}","Officials",null,2,2);format.Phases.Add(new FormatPhase("R","Regular",PhaseType.RoundRobin,PhaseRole.Regular,1,1,FixtureMode.BalancedRandom));var competition=new Competition("Officials",new Season((short)Random.Shared.Next(2100,30000),$"S{suffix}",null,null),new Division($"D{suffix}",(short)Random.Shared.Next(100,30000),Gender.Female),format,CompetitionPeriodType.Annual,null,null);var home=new TeamEntry(competition,new Team($"H{suffix}",Gender.Female,null),null);var away=new TeamEntry(competition,new Team($"A{suffix}",Gender.Female,null),null);var match=new Match(competition,competition.Phases[0],null,home,away,1,1);var refs=Enumerable.Range(0,4).Select(i=>new Referee(new Person(null,null,$"R{i}{suffix}","Official",null,null,null,null))).ToArray();db.Matches.Add(match);db.Referees.AddRange(refs);await db.SaveChangesAsync();return(match.MatchId,refs.Select(x=>x.RefereeId).ToArray());}
 private async Task SetStatus(int id,MatchStatus status){await using var scope=factory.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<LigaVolleyDbContext>();var match=await db.Matches.SingleAsync(x=>x.MatchId==id);typeof(Match).GetProperty(nameof(Match.Status))!.SetValue(match,status);await db.SaveChangesAsync();}
}
