using System.Net;using System.Net.Http.Json;using System.Text.Json;using System.Text.Json.Serialization;using LigaVolley.Application.Common;using LigaVolley.Application.People;using LigaVolley.Domain.People;
namespace LigaVolley.IntegrationTests;
public sealed class PeopleEndpointsTests(LigaVolleyApiFactory factory):IClassFixture<LigaVolleyApiFactory>
{
 private static readonly JsonSerializerOptions Json=CreateJson();
 private static JsonSerializerOptions CreateJson(){var options=new JsonSerializerOptions(JsonSerializerDefaults.Web);options.Converters.Add(new JsonStringEnumConverter());return options;}
 [Fact]public async Task Full_people_profiles_and_documents_flow(){var suffix=Guid.NewGuid().ToString("N")[..8];var created=await Create(new(null,null," Ana "," Zebra ",null,null,$"ana.{suffix}@example.com",null));Assert.True(created.Active);Assert.Empty(created.AdditionalDocuments);Assert.Null(created.Profiles.Player);
 var healthResponse=await factory.Client.PostAsJsonAsync($"/api/admin/people/{created.PersonId}/additional-documents",new CreatePersonAdditionalDocumentRequest(PersonAdditionalDocumentType.HealthCard,"HC",DateOnly.FromDateTime(DateTime.UtcNow.AddDays(-1)),DateOnly.FromDateTime(DateTime.UtcNow.AddDays(30)),null),Json);Assert.Equal(HttpStatusCode.Created,healthResponse.StatusCode);var health=(await healthResponse.Content.ReadFromJsonAsync<PersonAdditionalDocumentDto>(Json))!;
 var playerResponse=await factory.Client.PostAsync($"/api/admin/people/{created.PersonId}/player",null);Assert.Equal(HttpStatusCode.Created,playerResponse.StatusCode);var player=(await playerResponse.Content.ReadFromJsonAsync<PlayerDto>(Json))!;Assert.Equal(HealthCardStatus.Valid,player.HealthCard.Status);
 var coachResponse=await factory.Client.PostAsync($"/api/admin/people/{created.PersonId}/coach",null);Assert.Equal(HttpStatusCode.Created,coachResponse.StatusCode);var refereeResponse=await factory.Client.PostAsync($"/api/admin/people/{created.PersonId}/referee",null);Assert.Equal(HttpStatusCode.Created,refereeResponse.StatusCode);
 Assert.Equal(HttpStatusCode.Conflict,(await factory.Client.PostAsync($"/api/admin/people/{created.PersonId}/player",null)).StatusCode);
 var off=await factory.Client.PatchAsJsonAsync($"/api/admin/people/{created.PersonId}/active",new SetActiveRequest(false));Assert.False((await off.Content.ReadFromJsonAsync<PersonDto>(Json))!.Active);Assert.True((await factory.Client.GetFromJsonAsync<PlayerDto>($"/api/admin/players/{player.PlayerId}",Json))!.PlayerActive);
 var docOff=await factory.Client.PatchAsJsonAsync($"/api/admin/people/{created.PersonId}/additional-documents/{health.PersonAdditionalDocumentId}/active",new SetActiveRequest(false));docOff.EnsureSuccessStatusCode();Assert.Equal(HealthCardStatus.Missing,(await factory.Client.GetFromJsonAsync<PlayerDto>($"/api/admin/players/{player.PlayerId}",Json))!.HealthCard.Status);
 var list=await factory.Client.GetFromJsonAsync<PagedResult<PersonSummaryDto>>($"/api/admin/people?query=Zebra&page=1&pageSize=25",Json);Assert.Contains(list!.Items,x=>x.PersonId==created.PersonId);}
 [Fact]public async Task Validation_uniqueness_scope_and_no_delete_are_enforced(){var doc=Guid.NewGuid().ToString("N")[..12];var p=await Create(new(" ci ",doc,"A","Same",null,null,null,null));var duplicate=await factory.Client.PostAsJsonAsync("/api/admin/people",new CreatePersonRequest("CI",doc,"B","Other",null,null,null,null),Json);Assert.Equal(HttpStatusCode.Conflict,duplicate.StatusCode);Assert.Equal("person_document_already_exists",(await duplicate.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("code").GetString());
 var incomplete=await factory.Client.PostAsJsonAsync("/api/admin/people",new CreatePersonRequest("CI",null,"A","B",null,null,null,null),Json);Assert.Equal(HttpStatusCode.BadRequest,incomplete.StatusCode);var future=await factory.Client.PostAsJsonAsync("/api/admin/people",new CreatePersonRequest(null,null,"A","B",DateOnly.FromDateTime(DateTime.UtcNow.AddDays(1)),null,null,null),Json);Assert.Equal(HttpStatusCode.BadRequest,future.StatusCode);
 var d=(await (await factory.Client.PostAsJsonAsync($"/api/admin/people/{p.PersonId}/additional-documents",new CreatePersonAdditionalDocumentRequest(PersonAdditionalDocumentType.LeagueCard,null,null,null,null),Json)).Content.ReadFromJsonAsync<PersonAdditionalDocumentDto>(Json))!;var other=await Create(new(null,null,"X","Y",null,null,null,null));Assert.Equal(HttpStatusCode.NotFound,(await factory.Client.PutAsJsonAsync($"/api/admin/people/{other.PersonId}/additional-documents/{d.PersonAdditionalDocumentId}",new UpdatePersonAdditionalDocumentRequest(PersonAdditionalDocumentType.LeagueCard,null,null,null,null),Json)).StatusCode);Assert.Equal(HttpStatusCode.MethodNotAllowed,(await factory.Client.DeleteAsync($"/api/admin/people/{p.PersonId}")).StatusCode);}
 [Fact]public async Task Health_card_statuses_are_derived(){var p=await Create(new(null,null,"H","Cards",null,null,null,null));var player=(await (await factory.Client.PostAsync($"/api/admin/people/{p.PersonId}/player",null)).Content.ReadFromJsonAsync<PlayerDto>(Json))!;Assert.Equal(HealthCardStatus.Missing,player.HealthCard.Status);await factory.Client.PostAsJsonAsync($"/api/admin/people/{p.PersonId}/additional-documents",new CreatePersonAdditionalDocumentRequest(PersonAdditionalDocumentType.HealthCard,null,null,null,null),Json);Assert.Equal(HealthCardStatus.ValidityUnknown,(await factory.Client.GetFromJsonAsync<PlayerDto>($"/api/admin/players/{player.PlayerId}",Json))!.HealthCard.Status);}
 [Fact]public async Task OpenApi_documents_all_people_operations_and_no_delete(){var json=await factory.Client.GetStringAsync("/swagger/v1/swagger.json");using var doc=JsonDocument.Parse(json);var paths=doc.RootElement.GetProperty("paths");Assert.True(paths.TryGetProperty("/api/admin/people",out var people));Assert.True(people.TryGetProperty("get",out _));Assert.True(people.TryGetProperty("post",out _));Assert.False(people.TryGetProperty("delete",out _));Assert.True(paths.TryGetProperty("/api/admin/people/{personId}/additional-documents/{documentId}/active",out _));Assert.True(paths.TryGetProperty("/api/admin/players/{playerId}/active",out _));Assert.True(paths.TryGetProperty("/api/admin/coaches/{coachId}/active",out _));Assert.True(paths.TryGetProperty("/api/admin/referees/{refereeId}/active",out _));}
 [Fact]public async Task Concurrent_same_document_creates_exactly_one_person(){var number=$"RACE-{Guid.NewGuid():N}"[..30];var request=new CreatePersonRequest("CI",number,"Race","Person",null,null,null,null);var responses=await Task.WhenAll(factory.Client.PostAsJsonAsync("/api/admin/people",request,Json),factory.Client.PostAsJsonAsync("/api/admin/people",request,Json));Assert.Single(responses.Where(x=>x.StatusCode==HttpStatusCode.Created));Assert.Single(responses.Where(x=>x.StatusCode==HttpStatusCode.Conflict));var found=await factory.Client.GetFromJsonAsync<PagedResult<PersonSummaryDto>>($"/api/admin/people?documentType=CI&documentNumber={number}&page=1&pageSize=25",Json);Assert.Equal(1,found!.TotalCount);}
 private async Task<PersonDto>Create(CreatePersonRequest r){var response=await factory.Client.PostAsJsonAsync("/api/admin/people",r,Json);response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<PersonDto>(Json))!;}
}
