using LigaVolley.Application.Abstractions.Persistence;using LigaVolley.Domain.People;using Microsoft.EntityFrameworkCore;
namespace LigaVolley.Infrastructure.Persistence.Repositories;
internal sealed class PeopleRepository(LigaVolleyDbContext db):IPeopleRepository
{
 private IQueryable<Person> People(bool tracking=false){IQueryable<Person>q=db.People.Include(x=>x.AdditionalDocuments).Include(x=>x.Player).Include(x=>x.Coach).Include(x=>x.Referee);return tracking?q:q.AsNoTracking();}
 public async Task<(IReadOnlyList<Person>,int)> ListPeopleAsync(string? text,string? type,string? number,DateOnly? birth,bool? active,int page,int size,CancellationToken ct){var q=People();if(text is not null){var p=$"%{text}%";q=q.Where(x=>EF.Functions.Like(x.FirstName,p)||EF.Functions.Like(x.LastName,p)||EF.Functions.Like(x.FirstName+" "+x.LastName,p)||EF.Functions.Like(x.LastName+" "+x.FirstName,p));}if(type is not null)q=q.Where(x=>x.DocumentType==type&&x.DocumentNumber==number);if(birth.HasValue)q=q.Where(x=>x.BirthDate==birth);if(active.HasValue)q=q.Where(x=>x.Active==active);var total=await q.CountAsync(ct);var items=await q.OrderBy(x=>x.LastName).ThenBy(x=>x.FirstName).ThenBy(x=>x.PersonId).Skip((page-1)*size).Take(size).AsSplitQuery().ToListAsync(ct);return(items,total);}
 public Task<Person?> GetPersonAsync(int id,bool tracking,CancellationToken ct)=>People(tracking).AsSplitQuery().SingleOrDefaultAsync(x=>x.PersonId==id,ct);public Task<bool> DocumentExistsAsync(string t,string n,int? id,CancellationToken ct)=>db.People.AnyAsync(x=>x.DocumentType==t&&x.DocumentNumber==n&&(!id.HasValue||x.PersonId!=id),ct);public void Add(Person x)=>db.People.Add(x);
 public Task<PersonAdditionalDocument?> GetDocumentAsync(int p,int id,bool tracking,CancellationToken ct){IQueryable<PersonAdditionalDocument>q=db.PersonAdditionalDocuments;if(!tracking)q=q.AsNoTracking();return q.SingleOrDefaultAsync(x=>x.PersonId==p&&x.PersonAdditionalDocumentId==id,ct);}public void Add(PersonAdditionalDocument x)=>db.PersonAdditionalDocuments.Add(x);
 private static IQueryable<T> Search<T>(IQueryable<T> q,string? text,bool? active,System.Linq.Expressions.Expression<Func<T,Person>> person,System.Linq.Expressions.Expression<Func<T,bool>> profileActive){if(text is not null){var p=$"%{text}%";q=q.Where(x=>EF.Functions.Like(EF.Property<string>(EF.Property<Person>(x!,"Person"),"FirstName"),p)||EF.Functions.Like(EF.Property<string>(EF.Property<Person>(x!,"Person"),"LastName"),p));}if(active.HasValue)q=q.Where(active.Value?profileActive:Negate(profileActive));return q;}private static System.Linq.Expressions.Expression<Func<T,bool>> Negate<T>(System.Linq.Expressions.Expression<Func<T,bool>> e){var p=e.Parameters[0];return System.Linq.Expressions.Expression.Lambda<Func<T,bool>>(System.Linq.Expressions.Expression.Not(e.Body),p);}
 public Task<(IReadOnlyList<Player>,int)> ListPlayersAsync(string? q,bool? a,int p,int s,CancellationToken ct)=>Profiles(db.Players.Include(x=>x.Person).ThenInclude(x=>x.AdditionalDocuments),q,a,p,s,x=>x.Active,x=>x.Person.LastName,x=>x.Person.FirstName,ct);public Task<Player?> GetPlayerAsync(int id,bool tracking,CancellationToken ct)=>Profile(db.Players,id,tracking,x=>x.PlayerId,ct);public Task<bool> PlayerExistsAsync(int p,CancellationToken ct)=>db.Players.AnyAsync(x=>x.PersonId==p,ct);public void Add(Player x)=>db.Players.Add(x);
 public Task<(IReadOnlyList<Coach>,int)> ListCoachesAsync(string? q,bool? a,int p,int s,CancellationToken ct)=>Profiles(db.Coaches.Include(x=>x.Person),q,a,p,s,x=>x.Active,x=>x.Person.LastName,x=>x.Person.FirstName,ct);public Task<Coach?> GetCoachAsync(int id,bool tracking,CancellationToken ct)=>Profile(db.Coaches,id,tracking,x=>x.CoachId,ct);public Task<bool> CoachExistsAsync(int p,CancellationToken ct)=>db.Coaches.AnyAsync(x=>x.PersonId==p,ct);public void Add(Coach x)=>db.Coaches.Add(x);
 public Task<(IReadOnlyList<Referee>,int)> ListRefereesAsync(string? q,bool? a,int p,int s,CancellationToken ct)=>Profiles(db.Referees.Include(x=>x.Person).ThenInclude(x=>x.AdditionalDocuments),q,a,p,s,x=>x.Active,x=>x.Person.LastName,x=>x.Person.FirstName,ct);public Task<Referee?> GetRefereeAsync(int id,bool tracking,CancellationToken ct)=>Profile(db.Referees,id,tracking,x=>x.RefereeId,ct);public Task<bool> RefereeExistsAsync(int p,CancellationToken ct)=>db.Referees.AnyAsync(x=>x.PersonId==p,ct);public void Add(Referee x)=>db.Referees.Add(x);
 private static async Task<(IReadOnlyList<T>,int)> Profiles<T>(IQueryable<T> q,string? text,bool? active,int page,int size,System.Linq.Expressions.Expression<Func<T,bool>> act,System.Linq.Expressions.Expression<Func<T,string>> last,System.Linq.Expressions.Expression<Func<T,string>> first,CancellationToken ct)where T:class{if(text is not null){var p=$"%{text}%";q=q.Where(x=>EF.Functions.Like(EF.Property<string>(EF.Property<Person>(x,"Person"),"FirstName"),p)||EF.Functions.Like(EF.Property<string>(EF.Property<Person>(x,"Person"),"LastName"),p));}if(active.HasValue)q=q.Where(active.Value?act:Negate(act));var total=await q.CountAsync(ct);return(await q.AsNoTracking().OrderBy(last).ThenBy(first).Skip((page-1)*size).Take(size).AsSplitQuery().ToListAsync(ct),total);}
 private static Task<T?> Profile<T>(IQueryable<T> q,int id,bool tracking,System.Linq.Expressions.Expression<Func<T,int>> key,CancellationToken ct)where T:class{q=q.Include("Person.AdditionalDocuments");if(!tracking)q=q.AsNoTracking();var parameter=key.Parameters[0];var body=System.Linq.Expressions.Expression.Equal(key.Body,System.Linq.Expressions.Expression.Constant(id));return q.SingleOrDefaultAsync(System.Linq.Expressions.Expression.Lambda<Func<T,bool>>(body,parameter),ct);}
}
